### ISSUE TITLE
Responsive don't work when activate developer mode

### ISSUE THREAD

**Issue by robinhli** [OCA/web#1000]
When I install the responsive module. it works fine at normal mode. but when I activate the developoer mode (the url will have "debug " or "debug=assets"), the page can't be fully showed up. (only part of page is shown)
it seems it can't load a static css file. I checked the file at server side, it's there, under the web_responsive subdirectory (web_responsive/static/lib/css), I also tried to load this file at browser, it fails, can't load this css file.

The browser log show:
:8069/web_responsive/static/lib/css/drawer.3.2.0.css:1 Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)

the server side log show as follows:

2018-07-23 13:11:45,113 5433 INFO Cirque werkzeug: 192.168.31.83 - - [23/Jul/2018 13:11:45] "GET /web_responsive/static/src/js/web_responsive.js HTTP/1.1" 500 -
2018-07-23 13:11:45,118 5433 ERROR Cirque werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/p3/p3/lib/python3.4/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/home/p3/p3/lib/python3.4/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/home/wwwroot/odoo/odoo/service/server.py", line 252, in app
    return self.app(e, s)
  File "/home/wwwroot/odoo/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/home/wwwroot/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/home/wwwroot/odoo/odoo/http.py", line 1316, in __call__
    return self.dispatch(environ, start_response)
  File "/home/wwwroot/odoo/odoo/http.py", line 1290, in __call__
    return self.app(environ, start_wrapped)
  File "/home/p3/p3/lib/python3.4/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/home/wwwroot/odoo/odoo/http.py", line 1480, in dispatch
    result = ir_http._dispatch()
  File "/home/wwwroot/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/wwwroot/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/home/wwwroot/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/wwwroot/odoo/addons/http_routing/models/ir_http.py", line 390, in _dispatch
    return cls._handle_exception(routing_error)
  File "/home/wwwroot/odoo/addons/website/models/ir_http.py", line 181, in _handle_exception
    traceback=traceback.format_exc(),
  File "/usr/local/python/lib/python3.4/traceback.py", line 256, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/local/python/lib/python3.4/traceback.py", line 181, in format_exception
    return list(_format_exception_iter(etype, value, tb, limit, chain))
  File "/usr/local/python/lib/python3.4/traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "/usr/local/python/lib/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'

**Comment by robinhli** [comment]
This was a version downloaded on 2018.6.28.
I downloaded the latest version just now, and it works.

**Comment by pedrobaeza** [comment]
This is working correctly. It should be on your side.
