### ISSUE TITLE
[11.0] web_responsive

### ISSUE THREAD

**Issue by ghost** [OCA/web#1017]
After git-upgrade:
- Test with the differnet chatterpositions (none, normal, sided)
- with a -u upgrade from console,
- always this 500 Internal Server Error:

Error on request:
Traceback (most recent call last):
  File "/usr/share/odoo/lib/python3.6/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/share/odoo/lib/python3.6/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/share/odoo/odoo/odoo/service/wsgi_server.py", line 164, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/share/odoo/lib/python3.6/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/usr/share/odoo/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/share/odoo/odoo/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/share/odoo/odoo/odoo/http.py", line 1292, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/share/odoo/lib/python3.6/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/share/odoo/odoo/odoo/http.py", line 1490, in dispatch
    result = ir_http._dispatch()
  File "/usr/share/odoo/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/share/odoo/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/usr/share/odoo/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/share/odoo/odoo/addons/http_routing/models/ir_http.py", line 393, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/usr/share/odoo/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/usr/share/odoo/odoo/addons/website/models/ir_http.py", line 169, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/usr/share/odoo/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/share/odoo/odoo/odoo/http.py", line 770, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/share/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/share/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/usr/share/odoo/odoo/odoo/http.py", line 829, in dispatch
    r = self._call_function(**self.params)
  File "/usr/share/odoo/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/share/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/share/odoo/odoo/odoo/http.py", line 338, in checked_call
    result.flatten()
  File "/usr/share/odoo/odoo/odoo/http.py", line 1269, in flatten
    self.response.append(self.render())
  File "/usr/share/odoo/odoo/odoo/http.py", line 1262, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1195, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/share/odoo/odoo/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/usr/share/odoo/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1204, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/share/odoo/apps/website_theme_flexible/models/ir_qweb.py", line 21, in render
    **options)
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 271, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 349, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'chatter_position'
Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 342, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_171_203
  File "<template>", line 2, in body_call_content_202
KeyError: 'chatter_position'
Error to render compiling AST
KeyError: 'chatter_position'
Template: 171
Path: /templates/t/t/div
Node: <div class="o_main" t-attf-class="o_main o_chatter_position_{{ json.loads(session_info)['chatter_position'] }}">
                
            <div id="app-sidebar" class="app-sidebar-panel">
                <div class="app-sidebar navbar-collapse collapse">
                    <ul id="sidebar" class="app-sidebar-menu">
                        <li class="nav-item" t-as="menu" t-foreach="menu_data['children']">
                            <t t-set="debug_param" t-value="''"/>
                            <a t-att-href="'/web%s#menu_id=%s&amp;action=' % (debug_param, menu['id'])" t-att-class="'nav-link nav-toggle' if menu.get('children') else 'nav-link '" t-att-data-menu="menu['id']" t-att-data-menu-xmlid="menu.get('xmlid')" t-att-data-action-model="menu['action'] and menu['action'].split(',')[0] or None" t-att-data-action-id="menu['action'] and menu['action'].split(',')[1] or None">
                                <img t-attf-src="/web/image/ir.ui.menu/{{ menu['id'] }}/web_icon_data" t-att-alt="menu['name']" class="app-sidebar-menuitem" t-att-title="menu['name']"/>
                                <span class="title">
                                    <t t-esc="menu['name']"/>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        <div class="o_main_content"/>
            </div>

**Comment by ghost** [comment]
After downgrading web_responsive and backend_theme_v11 no problems.

**Comment by pedrobaeza** [comment]
Same answer as https://github.com/OCA/web/issues/1016#issuecomment-412006702
