### ISSUE TITLE
[V11] Error during installation of module

### ISSUE THREAD

**Issue by dsmerghetto** [OCA/web#1027]
I have this error during module installation in my Odoo 11 Enterprise server
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/srv/workspace/odoo-11/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/srv/workspace/odoo-11/odoo/addons/base/ir/ir_ui_view.py", line 330, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/srv/workspace/odoo-11/odoo/addons/base/ir/ir_ui_view.py", line 720, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/srv/workspace/odoo-11/odoo/addons/base/ir/ir_ui_view.py", line 669, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/srv/workspace/odoo-11/odoo/addons/base/ir/ir_ui_view.py", line 647, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/srv/workspace/odoo-11/odoo/addons/base/ir/ir_ui_view.py", line 509, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//div[hasclass('o_sub_menu')]">' cannot be located in parent view

Error context:
View `App Drawer - Web Client`
[view_id: 2320, xml_id: n/a, model: n/a, parent_id: 170]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/workspace/odoo-11/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/srv/workspace/odoo-11/odoo/tools/convert.py", line 722, in _tag_template
    return self._tag_record(record, data_node)
  File "/srv/workspace/odoo-11/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/srv/workspace/odoo-11/odoo/addons/base/ir/ir_model.py", line 1487, in _update
    record = record.create(values)
  File "/srv/workspace/odoo-11/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/srv/workspace/odoo-11/odoo/models.py", line 3381, in create
    self._fields[key].determine_inverse(record)
  File "/srv/workspace/odoo-11/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/srv/workspace/odoo-11/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/srv/workspace/odoo-11/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/srv/workspace/odoo-11/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/srv/workspace/odoo-11/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/srv/workspace/odoo-11/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nElement \'<xpath expr="//div[hasclass(\'o_sub_menu\')]">\' cannot be located in parent view\n\nError context:\nView `App Drawer - Web Client`\n[view_id: 2320, xml_id: n/a, model: n/a, parent_id: 170]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/workspace/odoo-11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/workspace/odoo-11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/srv/workspace/odoo-11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/srv/workspace/odoo-11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/srv/workspace/odoo-11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/workspace/odoo-11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/workspace/odoo-11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/srv/workspace/odoo-11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/srv/workspace/odoo-11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/srv/workspace/odoo-11/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/srv/workspace/odoo-11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/srv/workspace/odoo-11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/srv/workspace/odoo-11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/srv/workspace/odoo-11/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/srv/workspace/odoo-11/odoo/addons/base/module/module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/srv/workspace/odoo-11/odoo/addons/base/module/module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/srv/workspace/odoo-11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/srv/workspace/odoo-11/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/srv/workspace/odoo-11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/srv/workspace/odoo-11/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/srv/workspace/odoo-11/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/srv/workspace/odoo-11/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/srv/workspace/odoo-11/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/srv/workspace/odoo-11/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/srv/workspace/odoo-11/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/srv/workspace/odoo-11/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/srv/workspace/odoo-11/odoo/tools/convert.py", line 722, in _tag_template
    return self._tag_record(record, data_node)
  File "/srv/workspace/odoo-11/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/srv/workspace/odoo-11/odoo/addons/base/ir/ir_model.py", line 1487, in _update
    record = record.create(values)
  File "/srv/workspace/odoo-11/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/srv/workspace/odoo-11/odoo/models.py", line 3381, in create
    self._fields[key].determine_inverse(record)
  File "/srv/workspace/odoo-11/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/srv/workspace/odoo-11/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/srv/workspace/odoo-11/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/srv/workspace/odoo-11/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/srv/workspace/odoo-11/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/srv/workspace/odoo-11/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Element '<xpath expr="//div[hasclass('o_sub_menu')]">' cannot be located in parent view

Error context:
View `App Drawer - Web Client`
[view_id: 2320, xml_id: n/a, model: n/a, parent_id: 170]
None" while parsing None:14, near
<data inherit_id="web.webclient_bootstrap" name="App Drawer - Web Client">

        <xpath expr="//div[hasclass('o_sub_menu')]" position="replace"/>

        <xpath expr="//t[@t-set='head']" position="inside">
            <meta charset="utf-8"/>
            <meta http-equiv="cleartype" content="on"/>
            <meta name="MobileOptimized" content="320"/>
            <meta name="HandheldFriendly" content="True"/>
            <meta name="apple-mobile-web-app-capable" content="yes"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
        </xpath>

        <xpath expr="//nav[@id='oe_main_menu_navbar']" position="replace">

            <t t-set="body_classname" t-value="'drawer drawer--left o_web_client'"/>

            <header role="banner">
                <nav id="odooAppDrawer" class="app-drawer-nav drawer-nav" role="navigation">
                    <t t-call="web.menu"/>
                </nav>

                <nav class="navbar navbar-default main-nav" role="navigation" groups="base.group_user,base.group_portal">
                    <div class="container-fluid">

                        <div class="navbar-header">

                            <a class="drawer-toggle navbar-collapse collapse btn btn-default app-drawer-toggle" accesskey="A">
                                <span class="sr-only">Toggle App Drawer</span>
                                <i class="fa fa-th fa-lg app-drawer-icon-open" t-translation="off" aria-hidden="true"/>
                            </a>

                            <button type="button" class="app-drawer-toggle drawer-toggle pull-left navbar-toggle collapsed">
                                <span class="sr-only">Toggle App Drawer</span>
                                <div class="fa fa-th fa-lg app-drawer-icon-open"/>
                            </button>

                            <button type="button" id="odooMenuBarToggle" class="navbar-toggle collapsed pull-right" data-toggle="collapse" data-target="#odooMenuBarNav">
                                <span class="sr-only">Toggle Navigation</span>
                                <i class="fa fa-bars fa-lg" t-translation="off" aria-hidden="true"/>
                            </button>

                        </div>

                        <div class="collapse navbar-collapse" id="odooMenuBarNav" data-parent="#odooMenuBarToggle" aria-expanded="false">
                            <div class="o_sub_menu" groups="base.group_user,base.group_portal">
                                <t t-call="web.menu_secondary"/>
                            </div>
                        </div>
                    </div>
                    <div class="nav navbar-nav navbar-right navbar-systray o_menu_systray">
                        <ul class="nav navbar-nav navbar-right navbar-systray-item oe_user_menu_placeholder"/>
                        <ul class="nav navbar-nav navbar-right navbar-systray-item oe_systray"/>
                    </div>
                </nav>

            </header>

        </xpath>

        <xpath expr="//div[hasclass('o_main')]" position="attributes">
            <attribute name="t-attf-class">o_main o_chatter_position_{{ request.env.user.chatter_position or 'normal' }}</attribute>
        </xpath>

    </data>

**Comment by pedrobaeza** [comment]
Are you talking about `web_responsive`? That module is incompatible with `web_enterprise` module.

**Comment by pedrobaeza** [comment]
Closing as no response.
