### ISSUE TITLE
Web Responsive _ Template 'AppDrawerMenuSearchResults' not found

### ISSUE THREAD

**Issue by deebo2121** [OCA/web#1032]
When open search in menu items it gives this bug, Odoo v10.0 community edition

Uncaught Error: QWeb2: Template 'AppDrawerMenuSearchResults' not found

http://35.187.243.56:8069/web/content/490-1ac659d/web.assets_common.js:2908
Traceback:
Error: QWeb2: Template 'AppDrawerMenuSearchResults' not found
    at Object.exception (http://35.187.243.56:8069/web/content/490-1ac659d/web.assets_common.js:2908:7)
    at Engine._render (http://35.187.243.56:8069/web/content/490-1ac659d/web.assets_common.js:2953:103)
    at Engine.render (http://35.187.243.56:8069/web/content/490-1ac659d/web.assets_common.js:2949:151)
    at Class.showFoundMenus (http://35.187.243.56:8069/web/content/592-741144a/web.assets_backend.js:3443:1242)
    at Object.proxy (http://35.187.243.56:8069/web/content/490-1ac659d/web.assets_common.js:380:57)
    at Object.<anonymous> (http://35.187.243.56:8069/web/content/490-1ac659d/web.assets_common.js:547:681)
    at fire (http://35.187.243.56:8069/web/content/490-1ac659d/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://35.187.243.56:8069/web/content/490-1ac659d/web.assets_common.js:546:198)
    at Object.<anonymous> (http://35.187.243.56:8069/web/content/490-1ac659d/web.assets_common.js:547:874)
    at fire (http://35.187.243.56:8069/web/content/490-1ac659d/web.assets_common.js:541:299)

**Comment by pedrobaeza** [comment]
You should update the module in your DB.
