### ISSUE TITLE
web_responsive.MenuStatusbarButtons'

### ISSUE THREAD

**Issue by mokerosan** [OCA/web#1034]
I have the following error, some idea of ​​how to solve it? where can I get it or what module does it depend on?

Error:
Uncaught Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not found

**Comment by pedrobaeza** [comment]
Update the module in your DB and refresh the browser. Note that this is compatible with modern browsers, not with old ones like Internet Explorer. Edge is not tested though.

**Comment by SalouaSahnoun** [comment]
Hi,
i had the same error message after installing the web_responsive module,
I installed it in a virgin database, then I installed the odoo sales module then I tried to create a quote I got the following error message:
#############################################################################
Erreur:
Uncaught Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not found

http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:3689
Retraçage :
Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not found
at Object.exception (http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:3689:7)
at Engine._render (http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:3734:103)
at Engine.render (http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:3730:151)
at Class._renderHeaderButtons (http://test-odoo.test-novojob.com:8069/web/content/312-e1ab7d1/web.assets_backend.js:2360:502)
at Class._renderHeaderButtons (http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:3819:371)
at Class._renderTagHeader (http://test-odoo.test-novojob.com:8069/web/content/312-e1ab7d1/web.assets_backend.js:1406:359)
at Class._renderNode (http://test-odoo.test-novojob.com:8069/web/content/312-e1ab7d1/web.assets_backend.js:1396:246)
at Class.renderNode (http://test-odoo.test-novojob.com:8069/web/content/312-e1ab7d1/web.assets_backend.js:2594:51)
at Class.renderNode (http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:3819:371)
at Function..map..collect (http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:13:270)
############################################################################

**Comment by pedrobaeza** [comment]
You haven't restarted your Odoo service and refresh browser cache.

**Comment by SalouaSahnoun** [comment]
i restarted odoo-server, the postgresql service and i rebooted my machine, but the same problem precists

**Comment by pedrobaeza** [comment]
Well, as said, this is working properly on runbot, so there's something on your side that ruins it. Maybe an incompatibility with any module.

**Comment by SalouaSahnoun** [comment]
I thought about that too,
So, I installed the both modules (web_responsive & sale) in a new database (empty)

**Comment by pedrobaeza** [comment]
You can try on runbot and you will see that is working correctly.
