### ISSUE TITLE
odoo v11-web_responsive.MenuStatusbarButtons

### ISSUE THREAD

**Issue by jjlopezg** [OCA/web#1045]
http://localhost:8069/web/content/346-3ca6925/web.assets_common.js:3689
Rastreo de error:
Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not found
    at Object.exception (http://localhost:8069/web/content/346-3ca6925/web.assets_common.js:3689:7)
    at Engine._render (http://localhost:8069/web/content/346-3ca6925/web.assets_common.js:3734:103)
    at Engine.render (http://localhost:8069/web/content/346-3ca6925/web.assets_common.js:3730:151)
    at Class._renderHeaderButtons (http://localhost:8069/web/content/1067-73d118b/web.assets_backend.js:2733:502)
    at Class._renderHeaderButtons (http://localhost:8069/web/content/346-3ca6925/web.assets_common.js:3819:371)
    at Class._renderTagHeader (http://localhost:8069/web/content/1067-73d118b/web.assets_backend.js:1393:359)
    at Class._renderNode (http://localhost:8069/web/content/1067-73d118b/web.assets_backend.js:1383:246)
    at Class._renderNode (http://localhost:8069/web/content/1067-73d118b/web.assets_backend.js:2332:51)
    at Class._renderNode (http://localhost:8069/web/content/346-3ca6925/web.assets_common.js:3819:371)
    at Function._.map._.collect (http://localhost:8069/web/content/346-3ca6925/web.assets_common.js:13:270)
se puede arreglar?

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (https://runbot.odoo-community.org/runbot/162/11.0 - admin/admin), so please be sure you are installing the module properly.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by lalaki0921** [comment]
Hi,
I got the same problem after installing backend_theme_v11-11 and web_responsive modules. I deployed Odoo CE v11 via Bitnami on Google Platform. 
Any recommendation to save the problem? Thank you.

**Comment by jkbaseer** [comment]
Thanks for sharing that tip and helping us with that module. As the others I am facing the same issue as well where i **upgraded** the module according to your advice. 

Even after upgrading the module from the Odoo Apps install page, it doesn't work. It worked after going inside the server and trying **sudo service odoo restart**

**Comment by SalouaSahnoun** [comment]
Hi,
i had the same error message after installing the web_responsive module,
I installed it in a virgin database, then I installed the odoo sales module then I tried to create a quote I got the following error message:
#############################################################################
Erreur:
Uncaught Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not found

http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:3689
Retraçage :
Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not found
    at Object.exception (http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:3689:7)
    at Engine._render (http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:3734:103)
    at Engine.render (http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:3730:151)
    at Class._renderHeaderButtons (http://test-odoo.test-novojob.com:8069/web/content/312-e1ab7d1/web.assets_backend.js:2360:502)
    at Class._renderHeaderButtons (http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:3819:371)
    at Class._renderTagHeader (http://test-odoo.test-novojob.com:8069/web/content/312-e1ab7d1/web.assets_backend.js:1406:359)
    at Class._renderNode (http://test-odoo.test-novojob.com:8069/web/content/312-e1ab7d1/web.assets_backend.js:1396:246)
    at Class._renderNode (http://test-odoo.test-novojob.com:8069/web/content/312-e1ab7d1/web.assets_backend.js:2594:51)
    at Class._renderNode (http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:3819:371)
    at Function._.map._.collect (http://test-odoo.test-novojob.com:8069/web/content/308-660a963/web.assets_common.js:13:270)
############################################################################

**Comment by TheDailySpank** [comment]
```sudo /opt/bitnami/ctlscript.sh restart``` and a browser refresh worked for me.

**Comment by ahmad-mushtaq** [comment]
> `sudo /opt/bitnami/ctlscript.sh restart` and a browser refresh worked for me.

Restarting the odoo service worked for me.

On my ubuntu server I used the following command:

sudo service odoo11 restart

your's might be different command based on your installation
