### ISSUE TITLE
Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not found

### ISSUE THREAD

**Issue by marcoscamacho** [OCA/web#1050]
I install web_responsive-11.0.1.0.2 on /odoo-11.0.post20180918 and have this error when click on Sales/Sale order

Error:
Uncaught Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not found

http://192.168.10.35/web/content/321-a3b0ee1/web.assets_common.js:736
Rastreo de error:
Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not found
    at Object.exception (http://192.168.10.35/web/content/321-a3b0ee1/web.assets_common.js:736:10236)
    at Engine._render (http://192.168.10.35/web/content/321-a3b0ee1/web.assets_common.js:738:3980)
    at Engine.render (http://192.168.10.35/web/content/321-a3b0ee1/web.assets_common.js:738:3210)
    at Class._renderHeaderButtons (http://192.168.10.35/web/content/762-4664c60/web.assets_backend.js:2850:502)
    at Class._renderHeaderButtons (http://192.168.10.35/web/content/321-a3b0ee1/web.assets_common.js:738:24291)
    at Class._renderTagHeader (http://192.168.10.35/web/content/762-4664c60/web.assets_backend.js:1393:359)
    at Class._renderNode (http://192.168.10.35/web/content/762-4664c60/web.assets_backend.js:1383:246)
    at Class._renderNode (http://192.168.10.35/web/content/762-4664c60/web.assets_backend.js:2332:51)
    at Class._renderNode (http://192.168.10.35/web/content/321-a3b0ee1/web.assets_common.js:738:24291)
    at Function._.map._.collect (http://192.168.10.35/web/content/321-a3b0ee1/web.assets_common.js:3:2496)

**Comment by pedrobaeza** [comment]
You should probably not restart Odoo service or refresh page.
