### ISSUE TITLE
[10.0]web_ckeditor4 ValueError: Invalid attribute name u'x:str'

### ISSUE THREAD

**Issue by eversatis** [OCA/web#1116]
I use web_ckeditor4 for odoo 10 product website_description in backend. While everything works fine, the log keep output the following error when browsing product edited with ckeditor no matter back and front end. Anyone encountered this?
```
2018-11-29 01:46:56,664 20040 ERROR  odoo.tools.translate: Cannot translate malformed HTML, using source value instead
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/translate.py", line 313, in html_translate
    trans.process(root[0][0])               # html > body > div
  File "/odoo/odoo-server/odoo/tools/translate.py", line 252, in process
    child_trans.process(child)
  File "/odoo/odoo-server/odoo/tools/translate.py", line 252, in process
    child_trans.process(child)
  File "/odoo/odoo-server/odoo/tools/translate.py", line 252, in process
    child_trans.process(child)
  File "/odoo/odoo-server/odoo/tools/translate.py", line 252, in process
    child_trans.process(child)
  File "/odoo/odoo-server/odoo/tools/translate.py", line 265, in process
    self.done(self.serialize(node.tag, node.attrib, child_trans.get_done()))
  File "/odoo/odoo-server/odoo/tools/translate.py", line 275, in serialize
    elem = etree.tostring(etree.Element(tag, attrib), method='xml')
  File "src/lxml/lxml.etree.pyx", line 2998, in lxml.etree.Element (src/lxml/lxml.etree.c:80607)
  File "src/lxml/apihelpers.pxi", line 135, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17604)
  File "src/lxml/apihelpers.pxi", line 123, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17452)
  File "src/lxml/apihelpers.pxi", line 305, in lxml.etree._initNodeAttributes (src/lxml/lxml.etree.c:19986)
  File "src/lxml/apihelpers.pxi", line 315, in lxml.etree._addAttributeToNode (src/lxml/lxml.etree.c:20177)
  File "src/lxml/apihelpers.pxi", line 1638, in lxml.etree._attributeValidOrRaise (src/lxml/lxml.etree.c:35289)
ValueError: Invalid attribute name u'x:str'
```

**Comment by eversatis** [comment]
Anyone else encountered such an issue?

**Comment by pedrobaeza** [comment]
I would say this editor is not too much used since the inclusion of SummerEditor in Odoo core.

**Comment by eversatis** [comment]
But this is extremely useful if you have tens thousands products with simple html description which you can add and edit in backend odoo at the same time. The SummerEditor is surely cool when you have only a few products which need elegant details. I truely believe it is very useful if odoo eCommerce grow bigger.

Thank you

**Comment by pedrobaeza** [comment]
@frankmiao2015 for editing product description in e-commerce, you already have website builder, and its use is increased in newer versions.
