### ISSUE TITLE
Error while changing view from timeline to another and backward  

### ISSUE THREAD

**Issue by tglukhov** [OCA/web#1138]
Hello everyone, 

There is a problem with the view timeline in odoo V12, timeline V12

steps to reproduce : 
- open timeline view
- change view to any different
(- you can switch to any other view except timeline as many times as you want)
- back to view timeline 
the everything is frozen, you need to reload page 

message error : 
```
Error:
Uncaught TypeError: Cannot read property 'then' of undefined

http://localhost:8069/web/static/src/js/chrome/action_manager_act_window.js:650
Traceback:
TypeError: Cannot read property 'then' of undefined
at http://localhost:8069/web/static/src/js/chrome/action_manager_act_window.js:650:69
at http://localhost:8069/web/static/lib/jquery/jquery.js:3276:89
at fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)
at Object.add [as done] (http://localhost:8069/web/static/lib/jquery/jquery.js:3165:49)
at Array. (http://localhost:8069/web/static/lib/jquery/jquery.js:3275:77)
at Function.each (http://localhost:8069/web/static/lib/jquery/jquery.js:383:58)
at Object. (http://localhost:8069/web/static/lib/jquery/jquery.js:3272:56)
at Function.Deferred (http://localhost:8069/web/static/lib/jquery/jquery.js:3332:30)
at Object.then (http://localhost:8069/web/static/lib/jquery/jquery.js:3271:55)
at Object. (http://localhost:8069/web/static/src/js/chrome/action_manager_act_window.js:649:68)

```

**Comment by cvinh** [comment]
Please give us which version of web_timeline you are using

**Comment by pedrobaeza** [comment]
And Odoo version.

**Comment by pedrobaeza** [comment]
Also the traceback doesn't serve for anything if you are not in debug with assets mode.

**Comment by tglukhov** [comment]
oh yeah, sorry, 
the odoo version is v12 and web_timeline is a OCA module, also version 12. 

here is the error message in debug=assets mode 
Error:
Uncaught TypeError: Cannot read property 'then' of undefined

http://localhost:8069/web/static/src/js/chrome/action_manager_act_window.js:650
Traceback:
TypeError: Cannot read property 'then' of undefined
    at http://localhost:8069/web/static/src/js/chrome/action_manager_act_window.js:650:69
    at http://localhost:8069/web/static/lib/jquery/jquery.js:3276:89
    at fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.add [as done] (http://localhost:8069/web/static/lib/jquery/jquery.js:3165:49)
    at Array.<anonymous> (http://localhost:8069/web/static/lib/jquery/jquery.js:3275:77)
    at Function.each (http://localhost:8069/web/static/lib/jquery/jquery.js:383:58)
    at Object.<anonymous> (http://localhost:8069/web/static/lib/jquery/jquery.js:3272:56)
    at Function.Deferred (http://localhost:8069/web/static/lib/jquery/jquery.js:3332:30)
    at Object.then (http://localhost:8069/web/static/lib/jquery/jquery.js:3271:55)
    at Object.<anonymous> (http://localhost:8069/web/static/src/js/chrome/action_manager_act_window.js:649:68)

**Comment by tglukhov** [comment]
@pedrobaeza so what do you think about this? Do you have some clues for resolving this problem?

**Comment by pedrobaeza** [comment]
Sorry but no, I'm not the one that can solve the problem. I only manage the community and guards that issues are correctly notified.

**Comment by tglukhov** [comment]
Thank you however !

**Comment by cvinh** [comment]
@tglukhov you should ask @tarteo who is author

**Comment by tglukhov** [comment]
Thank you @tarteo for fixing this issue, it can be closed now. 

Regards
