### ISSUE TITLE
[10.0] [web_responsive] Uncaught TypeError: this.$el.drawer is not a function 

### ISSUE THREAD

**Issue by manuelpgs** [OCA/web#1235]
**#branch 10**
**#web_responsive 10.0.1.2.3**

After installing the module Web Responsive 10.0.1.2.3, I got this error:

**Title:** Uncaught TypeError: this.$el.drawer is not a function

**Error Body:**

`https://dominio.com/web/content/3103-2554bcf/web.assets_backend.js:2659
Traceback:
TypeError: this.$el.drawer is not a function
    at Class.initDrawer (https://dominio.com/web/content/3103-2554bcf/web.assets_backend.js:2659:2372)
    at Class.init (https://dominio.com/web/content/3103-2554bcf/web.assets_backend.js:2659:1671)
    at new Class (https://dominio.com/web/content/3003-c1519ad/web.assets_common.js:3016:65)
    at Class.<anonymous> (https://dominio.com/web/content/3103-2554bcf/web.assets_backend.js:2673:156)
    at Class.trigger (https://dominio.com/web/content/3003-c1519ad/web.assets_common.js:3105:180)
    at Class.trigger (https://dominio.com/web/content/3003-c1519ad/web.assets_common.js:3109:148)
    at Array.<anonymous> (https://dominio.com/web/content/3103-2554bcf/web.assets_backend.js:1717:1833)
    at Array.<anonymous> (https://dominio.com/web/content/3003-c1519ad/web.assets_common.js:547:681)
    at fire (https://dominio.com/web/content/3003-c1519ad/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://dominio.com/web/content/3003-c1519ad/web.assets_common.js:546:198)`

Also I can see this warning yellow message in the top page:

**Could not get content for /web_responsive/static/lib/css/drawer.3.2.2.css defined in bundle 'web.assets_backend**

![Screenshot 2019-04-02 18 10 01](https://user-images.githubusercontent.com/1145973/55439444-9d960c80-5572-11e9-8ef5-70e1cd94ed38.png)

**Comment by tarteo** [comment]
Sounds like you installed it incorrectly (version, restart, etc)? It works on Runbot.

Provide the ?debug=assets traceback otherwise it's not clear what the error is.

**Comment by manuelpgs** [comment]
Hi @tarteo  thank you for your answer.  

Attached the output with ?debug=assets enable.     I notice that it works in another server but don't in my server.   Any tips? 

![Screenshot 2019-04-09 11 36 55](https://user-images.githubusercontent.com/1145973/55814295-36b9ab80-5abc-11e9-82f1-93349e37fe9d.png)

**Comment by tarteo** [comment]
@herohat Not really, just check if your installation is not broken.

**Comment by manuelpgs** [comment]
@tarteo what test I should do?  In my ODOO installation, all seems to be working fine.  I can install and update modules and use it normally.

**Comment by edgarpaez** [comment]
Hi @herohat.
I had the same issue. It was my .gitignore file that excludes the /lib directory. Delete that line from your .gitignore and it will work again.

**Comment by manuelpgs** [comment]
Hi @edgarpaez you were totally right! It was in my .gitignore too.  Actually, I didn't realize that in my screenshot, there is a warning message with a yellow background telling me that can't load the file drawer.3.2.2.css in the path within the lib directory, and of course, there was also missing to load the js files.

Thank you for your advice.

**Comment by darshan-odoo** [comment]
@herohat That's right, the files in /lib directory was getting ignored. Removing it does resolve the issue, thanks!

![image](https://user-images.githubusercontent.com/42735016/62003510-c6e83300-b135-11e9-8b10-454b6f92640f.png)
