### ISSUE TITLE
[12.0] web_edit_user_filter: Error on pivot view

### ISSUE THREAD

**Issue by serCliff** [OCA/web#1261]
When I click on pivot view not shows any error but when I use some of filter on some view throw me an error that throws:

uncaught TypeError: Cannot read property 'attrs' of null odoo

**Comment by tarteo** [comment]
I cannot reproduce this error. Can you make a video of the exact steps you're taking.

**Comment by CasVissers-360ERP** [comment]
I can confirm this issue. Traceback:
`Uncaught Error: QWeb2 - template['web_edit_user_filter.Popover']: Runtime Error: TypeError: Cannot read property 'attrs' of null
https://customer.com/web/content/27834-713eac4/web.assets_common.js:3374
Traceback:
Error: QWeb2 - template['web_edit_user_filter.Popover']: Runtime Error: TypeError: Cannot read property 'attrs' of null
    at Object.exception (https://customer.com/web/content/27834-713eac4/web.assets_common.js:3374:7)
    at Engine.eval (eval at _render (https://customer.com/web/content/27834-713eac4/web.assets_common.js:3416:73), <anonymous>:25:29)
    at Engine._render (https://customer.com/web/content/27834-713eac4/web.assets_common.js:3415:296)
    at Engine.render (https://customer.com/web/content/27834-713eac4/web.assets_common.js:3415:151)
    at Class._renderPopover (https://customer.com/web/content/34810-32f55d3/web.assets_backend.js:4316:153)
    at https://customer.com/web/content/34810-32f55d3/web.assets_backend.js:4317:64
    at Function._.each._.forEach (https://customer.com/web/content/27834-713eac4/web.assets_common.js:12:558)
    at Class.renderFacets (https://customer.com/web/content/34810-32f55d3/web.assets_backend.js:4316:737)
    at Class.renderFacets (https://customer.com/web/content/27834-713eac4/web.assets_common.js:3541:371)
    at child.<anonymous> (https://customer.com/web/content/27834-713eac4/web.assets_common.js:3643:11)`

The traceback is shown when you open the sales - reporting menu.

**Comment by CasVissers-360ERP** [comment]
@tarteo Any update here? I can help with reproducing if you want?

**Comment by tarteo** [comment]
@CasVissers Nope, too busy.

**Comment by olaf-wagner** [comment]
I have this issue, too.
