### ISSUE TITLE
[12.0] web_export_view

### ISSUE THREAD

**Issue by smurf-U** [OCA/web#1359]
Error:
Uncaught Error: QWeb2: Template 'WebExportTreeViewXls' not found

http://localhost:8069/web/content/505-b19e372/web.assets_common.js:3374
Traceback:
Error: QWeb2: Template 'WebExportTreeViewXls' not found
    at Object.exception (http://localhost:8069/web/content/505-b19e372/web.assets_common.js:3374:7)
    at Engine._render (http://localhost:8069/web/content/505-b19e372/web.assets_common.js:3419:103)
    at Engine.render (http://localhost:8069/web/content/505-b19e372/web.assets_common.js:3415:151)
    at Object.<anonymous> (http://localhost:8069/web/content/519-d06622e/web.assets_backend.js:3586:617)
    at Object.<anonymous> (http://localhost:8069/web/content/505-b19e372/web.assets_common.js:802:681)
    at fire (http://localhost:8069/web/content/505-b19e372/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/505-b19e372/web.assets_common.js:801:198)
    at Object.deferred.(anonymous function) (http://localhost:8069/web/content/505-b19e372/web.assets_common.js:803:56)
    at fire (http://localhost:8069/web/content/505-b19e372/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/505-b19e372/web.assets_common.js:801:198)

**Comment by pedrobaeza** [comment]
Steps to reproduce in OCA runbot?

**Comment by meigallodixital** [comment]
The steps to reproduce is to install it and enter any view with view_type = list. We have tested it with hr.employe or hr.attendance and the error is fail. It gives error but the view if it is correct in background. All modules are updated.

**Comment by pedrobaeza** [comment]
Have you tried on OCA runbot?

**Comment by meigallodixital** [comment]
On runbot (https://runbot.odoo-community.org/runbot/162/12.0) works ok :\ 
I remove folder from addons and clone from github, and works too. 

This issue can be close. Thanks :)

**Comment by pedrobaeza** [comment]
Yes, that's what I supposed.
