### ISSUE TITLE
Webtime not working in the chrome mobile browser

### ISSUE THREAD

**Issue by julius3419** [OCA/web#1488]
module: web_timeline
version: 12.0

**Steps to reproduce**
I'm testing in the Android mobile browser, and found this issue.
As soon as i click on the "timeline" icon view, it throws the error below.

Error:
Uncaught TypeError: Cannot read property 'icon' of undefined

http://localhost:8069/web/content/1767-2bb842a/web.assets_backend.js:1293
Traceback:
TypeError: Cannot read property 'icon' of undefined
    at Class._renderSwitchButtons (http://localhost:8069/web/content/1767-2bb842a/web.assets_backend.js:1293:695)
    at Class._renderControlPanelElements (http://localhost:8069/web/content/1767-2bb842a/web.assets_backend.js:1291:390)
    at Class.start (http://localhost:8069/web/content/1767-2bb842a/web.assets_backend.js:1283:1427)
    at Class.prototype.<computed> [as start] (http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:3538:488)
    at http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:3684:52
    at http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:802:681
    at fire (http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:796:299)
    at Object.add [as done] (http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:797:467)
    at Array.<anonymous> (http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:802:649)
    at Function.each (http://localhost:8069/web/content/1368-f9f595c/web.assets_common.js:625:767)
![mobile_browser_android_error](https://user-images.githubusercontent.com/4618029/72489956-bac17080-3850-11ea-8bf6-19bbaa61c1dd.png)

**Current behavior**

**Expected behavior**

**Comment by pedrobaeza** [comment]
Yeah, for now timeline is not compatible with mobile.

**Comment by julius3419** [comment]
Thanks for the quick response. Timeline is such a great feature.
Is there any plan to make it compatible?

**Comment by pedrobaeza** [comment]
Not that I know.
