### ISSUE TITLE
[13.0] web_advanced_search fails on Add custom filter

### ISSUE THREAD

**Issue by Rad0van** [OCA/web#1604]
When trying to add custom filter it fails in browser with following:
`Uncaught TypeError: Cannot read property 'model' of undefined
http://localhost:8069/web/content/639-96a2333/web.assets_backend.js:3531
Traceback:
TypeError: Cannot read property 'model' of undefined
    at Class.init (http://localhost:8069/web/content/639-96a2333/web.assets_backend.js:3531:2619)
    at Class.prototype.<computed> [as init] (http://localhost:8069/web/content/632-d7d4839/web.assets_common.js:3861:488)
    at new Class (http://localhost:8069/web/content/632-d7d4839/web.assets_common.js:3862:65)
    at Class.select_field (http://localhost:8069/web/content/639-96a2333/web.assets_backend.js:1593:88)
    at Class.changed (http://localhost:8069/web/content/639-96a2333/web.assets_backend.js:1591:1377)
    at HTMLSelectElement.<anonymous> (http://localhost:8069/web/content/632-d7d4839/web.assets_common.js:3945:11)
    at HTMLDivElement.dispatch (http://localhost:8069/web/content/632-d7d4839/web.assets_common.js:1024:447)
    at HTMLDivElement.elemData.handle (http://localhost:8069/web/content/632-d7d4839/web.assets_common.js:1010:166)`

It happens especially upon selecting one2many, many2one or many2many field. The error in browser's (Chromium 81.0.4044.138 on Kubuntu) console is following:
`web.assets_backend.js:3531 Uncaught TypeError: Cannot read property 'model' of undefined
    at Class.init (web.assets_backend.js:3531)
    at Class.prototype.<computed> [as init] (web.assets_common.js:3861)
    at new Class (web.assets_common.js:3862)
    at Class.select_field (web.assets_backend.js:1593)
    at Class.changed (web.assets_backend.js:1591)
    at HTMLSelectElement.<anonymous> (web.assets_common.js:3945)
    at HTMLDivElement.dispatch (web.assets_common.js:1024)
    at HTMLDivElement.elemData.handle (web.assets_common.js:1010)
init @ web.assets_backend.js:3531
prototype.<computed> @ web.assets_common.js:3861
Class @ web.assets_common.js:3862
select_field @ web.assets_backend.js:1593
changed @ web.assets_backend.js:1591
(anonymous) @ web.assets_common.js:3945
dispatch @ web.assets_common.js:1024
elemData.handle @ web.assets_common.js:1010`

This was tested on freshly installed database with current (pulled from github) version of Odoo and web_advanced_serach. It works fine on 12.0

**Comment by pedrobaeza** [comment]
Is this reproducible on runbot? (see the badge on the README for accesing it)

**Comment by Rad0van** [comment]
> Is this reproducible on runbot? (see the badge on the README for accesing it)

Yep, the same result.
![image](https://user-images.githubusercontent.com/19169467/82301724-f152f780-99b8-11ea-842e-d73b230336b3.png)

**Comment by Rad0van** [comment]
On 12.0 it works just fine (it happens when you try to select any one2many, many2one or many2many field):
![image](https://user-images.githubusercontent.com/19169467/82302372-ccab4f80-99b9-11ea-9449-186768bb90ce.png)

**Comment by Tardo** [comment]
Thanks for report, should be fixed here: https://github.com/OCA/web/pull/1606

**Comment by Rad0van** [comment]
> Thanks for report, should be fixed here: #1606

Seems to work here on local installation. Guess the runbot gets synchronized later. Thanx.
