### ISSUE TITLE
traceback info with runbot on "settings" menu

### ISSUE THREAD

**Issue by bjoliveau** [OCA/web#183]
Get this traceback in http://3110944-8-0-206567.runbot1.odoo-community.org

Odoo Server Error

Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3110944-8-0-206567/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3110944-8-0-206567/openerp/http.py", line 1413, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/srv/openerp/instances/openerp-oca-runbot/sandbox/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by pedrobaeza** [comment]
No news, so I close.
