### ISSUE TITLE
can't open in Local Models

### ISSUE THREAD

**Issue by alanljj** [OCA/web#189]
after installed, I can't open it in Local models, here is pop error message:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3141, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3176, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3354, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/odoo/openerp/osv/fields.py", line 1468, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 186, in _get_desc
    output = publish_string(source=module.description or '', settings_overrides=overrides, writer=MyWriter())
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/core.py", line 414, in publish_string
    enable_exit_status=enable_exit_status)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/readers/**init**.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/parsers/rst/**init**.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 1135, in indent
    elements = self.block_quote(indented, line_offset)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 1150, in block_quote
    self.nested_parse(blockquote_lines, line_offset, blockquote)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2720, in underline
    source=src, line=srcline)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/utils/**init**.py", line 235, in severe
    return self.system_message(self.SEVERE_LEVEL, _args, *_kwargs)
  File "/home/odoo/odoo/lib/python2.7/site-packages/docutils/utils/**init**.py", line 193, in system_message
    raise SystemMessage(msg, level)
SystemMessage: <string>:19: (SEVERE/4) Unexpected section title.
# Usage

**Comment by dreispt** [comment]
Your traceback seems to be related to rendering an RST module description to HTML.
Where you trying to see a module in form view? Which module?

**Comment by alanljj** [comment]
Thank you for your reply. The model is Web Option Auto Color / web_option_auto_color.

I just click Setting - Models - Local Models, then click the icon of Web Option Auto Color

**Comment by dreispt** [comment]
I reproduced the issue:

```
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2721, in underline
    source=src, line=srcline)
  File "/usr/lib/python2.7/dist-packages/docutils/utils/__init__.py", line 235, in severe
    return self.system_message(self.SEVERE_LEVEL, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/docutils/utils/__init__.py", line 193, in system_message
    raise SystemMessage(msg, level)
SystemMessage: <string>:19: (SEVERE/4) Unexpected section title.

Usage
=====
```

**Comment by pedrobaeza** [comment]
I have fixed it directly due to the severity.

**Comment by LiuSir666vw** [comment]
hi,dreisppt.
did u solved the issue of "SystemMessage: :19: (SEVERE/4) Unexpected section title."?
is it a bug here?

**Comment by LiuSir666vw** [comment]
@dreispt @pedrobaeza 
hi,
did u solved the issue of "SystemMessage: :19: (SEVERE/4) Unexpected section title."?
is it a bug here?

**Comment by pedrobaeza** [comment]
Yes, read the history of the issue
