### ISSUE TITLE
TypeError: Cannot read property 'folded' of undefined when create a lead from mobile view [with own documents access rights]

### ISSUE THREAD

**Issue by hardikanavadia** [OCA/web#1899]
Created a user with "Own document" access rights and when create a new lead from kanban view it shows below error:

Error:

Traceback:
TypeError: Cannot read property 'folded' of undefined
at Class._onCloseQuickCreate (http://1xx.xx.xx.xyz:8069/web/content/1345-6b8cf64/web.assets_backend.js:6259:131)
at Class.<anonymous> (http://1xx.xx.xx.xyz:8069/web/content/1344-f592bd8/web.assets_common.js:4763:11)
at Class.trigger (http://1xx.xx.xx.xyz:8069/web/content/1344-f592bd8/web.assets_common.js:4761:180)
at Class._trigger_up (http://1xx.xx.xx.xyz:8069/web/content/1344-f592bd8/web.assets_common.js:4767:378)
at Class._trigger_up (http://1xx.xx.xx.xyz:8069/web/content/1344-f592bd8/web.assets_common.js:4767:462)
at Class.trigger_up (http://1xx.xx.xx.xyz:8069/web/content/1344-f592bd8/web.assets_common.js:4767:280)
at Class.addQuickCreate (http://1xx.xx.xx.xyz:8069/web/content/1345-6b8cf64/web.assets_backend.js:2420:6)
at Class.addQuickCreate (http://1xx.xx.xx.xyz:8069/web/content/1345-6b8cf64/web.assets_backend.js:6247:45)
at http://1xx.xx.xx.xyz:8069/web/content/1345-6b8cf64/web.assets_backend.js:2468:368
at async Class._removeSampleData (http://1xx.xx.xx.xyz:8069/web/content/1345-6b8cf64/web.assets_backend.js:1340:764)

**Comment by pedrobaeza** [comment]
Unless you prove this has something to do with any of the modules of this repository, we can't do anything, so closing meanwhile.

**Comment by hardikanavadia** [comment]
Sure @pedrobaeza 
Above error is producible when you install web_responsive module. and particularly mobile view

**Comment by pedrobaeza** [comment]
But what have to do "Own document" permission with `web_responsive`?
