### ISSUE TITLE
[10.0] web_advanced_search_x2x:Uncaught Error: cannot call methods on autocomplete prior to initialization; attempted to call method 'widget'

### ISSUE THREAD

**Issue by KothiyaRajeshEnvertis** [OCA/web#2008]
odoov10:New database installing new latest OCA version web_advanced_search_x2x(10.0.2.0.3) and web_widget_domain_v11(10.0.1.0.1) modules getting custom filter error.

create error steps:
install web_advanced_search_x2x version 10 module,
search bar search relational fields m2m,o2m,m2o with custom search filter like companies is not set

Error:

Uncaught Error: cannot call methods on autocomplete prior to initialization; attempted to call method 'widget'

http://localhost:8069/web/content/345-8b420e0/web.assets_common.js:364
Traceback:
Error: cannot call methods on autocomplete prior to initialization; attempted to call method 'widget'
    at Function.error (http://localhost:8069/web/content/345-8b420e0/web.assets_common.js:364:130)
    at HTMLInputElement.<anonymous> (http://localhost:8069/web/content/345-8b420e0/web.assets_common.js:1024:24)
    at Function.each (http://localhost:8069/web/content/345-8b420e0/web.assets_common.js:370:767)
    at jQuery.fn.init.each (http://localhost:8069/web/content/345-8b420e0/web.assets_common.js:358:643)
    at jQuery.fn.init.$.fn.<computed> [as autocomplete] (http://localhost:8069/web/content/345-8b420e0/web.assets_common.js:1023:253)
    at Class.<anonymous> (http://localhost:8069/web/content/362-430b2b2/web.assets_backend.js:2318:2204)
    at Class.trigger (http://localhost:8069/web/content/345-8b420e0/web.assets_common.js:3105:180)
    at Class.trigger (http://localhost:8069/web/content/345-8b420e0/web.assets_common.js:3109:148)
    at HTMLHtmlElement.<anonymous> (http://localhost:8069/web/content/345-8b420e0/web.assets_common.js:3252:446)
    at HTMLHtmlElement.dispatch (http://localhost:8069/web/content/345-8b420e0/web.assets_common.js:637:451)

![Screenshot (162)](https://user-images.githubusercontent.com/88818867/130451232-3de270f0-885d-47fb-bc32-76c716c66279.png)

help me please @pedrobaeza @Yajo @simahawk 
related #676

**Comment by pedrobaeza** [comment]
Sorry, too old version for us and we are not working anymore on such version.

**Comment by KothiyaRajeshEnvertis** [comment]
Thanks for response
