### ISSUE TITLE
[14.0] web_tree_many2one_clickable error when using context

### ISSUE THREAD

**Issue by alessandro-fiorino** [OCA/web#2020]
If the m2o field has a context depending on another field, a javascript error is thrown
.i.e.
`<field name="supplier_id_final" invisible="1"/>
<field name="purchase_order_id" context="{'default_partner_id': supplier_id_final }"/>
`

When clicking on the >> button of the purchase_order_id column, I get a javascript traceback.
It was working without problems in V13

Traceback:
Error: NameError: name 'supplier_id_final' is not defined
    at PY_ensurepy (https://test-14.dev.odoo.com/web/static/lib/py.js/lib/py.js:370:19)
    at Object.py.evaluate (https://test-14.dev.odoo.com/web/static/lib/py.js/lib/py.js:1352:20)
    at Object.py.evaluate (https://test-14.dev.odoo.com/web/static/lib/py.js/lib/py.js:1436:24)
    at Object.py.eval (https://test-14.dev.odoo.com/web/static/lib/py.js/lib/py.js:1471:19)
    at https://test-14.dev.odoo.com/web/static/src/js/core/py_utils.js:122:28
    at iterator (https://test-14.dev.odoo.com/web/static/lib/underscore/underscore.js:176:16)
    at Function.<anonymous> (https://test-14.dev.odoo.com/web/static/lib/underscore/underscore.js:191:14)
    at _.<computed> [as reduce] (https://test-14.dev.odoo.com/web/static/lib/underscore/underscore.js:1484:34)
    at eval_contexts (https://test-14.dev.odoo.com/web/static/src/js/core/py_utils.js:110:24)
    at https://test-14.dev.odoo.com/web/static/src/js/core/py_utils.js:126:25

**Comment by MihranThalhath** [comment]
@alessandro-fiorino

The change introduced in #1961 is causing this error I guess. Try removing it and check. I am not sure why this change was added though.

**Comment by aqeebimtiaz-bista** [comment]
> @alessandro-fiorino
> 
> The change introduced in #1961 is causing this error I guess. Try removing it and check. I am not sure why this change was added though.

In my Purchase Order tree, `product_id` field has `'partner_id':parent.partner_id, 'quantity':product_qty,....}` in `context`. When clicking on the button, results the same error.

Removing the `context` solved my issue for me, temporarily. 
But how can I get the `context` properly?

**Comment by aqeebimtiaz** [comment]
> @alessandro-fiorino
> 
> The change introduced in #1961 is causing this error I guess. Try removing it and check. I am not sure why this change was added though.

In my Purchase Order form view, `product_id` field has `'partner_id':parent.partner_id, 'quantity':product_qty,....}` in `context`. When clicking on the button, results the same error.

Removing the `context` solved the issue for me, temporarily. 
But how can I pass the `context` properly in `do_action()`?
