### ISSUE TITLE
web_group_expland.Buttons not found

### ISSUE THREAD

**Issue by emiliosj** [OCA/web#2043]
Hi,

I get this error after installing the module: https://odoo-community.org/shop/product/group-expand-buttons-2639#attr=11722

This is what I get:

Traceback:
Error: QWeb2: Template 'web_group_expand.Buttons' not found
    at Object.exception (https://tabudesignsh.odoo.com/web/content/76365-c775c10/web.assets_common.js:4407:7)
    at Engine._render (https://tabudesignsh.odoo.com/web/content/76365-c775c10/web.assets_common.js:4452:103)
    at Engine.render (https://tabudesignsh.odoo.com/web/content/76365-c775c10/web.assets_common.js:4448:151)
    at Class.start (https://tabudesignsh.odoo.com/web/content/76383-a5dad1f/web.assets_backend.js:12162:189)
    at Class.start (https://tabudesignsh.odoo.com/web/content/76365-c775c10/web.assets_common.js:4645:616)
    at https://tabudesignsh.odoo.com/web/content/76365-c775c10/web.assets_common.js:4984:52

I'm using Odoo 14 on odoo.sh

Any suggestions?

Thanks!

**Comment by pedrobaeza** [comment]
It seems an error on your deployment. Are you able to reproduce the problem in OCA runbot? Are you trying to import the module instead of installing the regular way?
