### ISSUE TITLE
[14.0] web_advanced_search: Traceback when adding a custom filter

### ISSUE THREAD

**Issue by RensVerachtert** [OCA/web#2218]
## Module
web_advanced_search

## Describe the bug
When adding a custom filter (not an advanced filter) on the field that is used by default (so when creating a custom filter without changing the field), selecting the option `is equal to` or `is not equal to` will generate following traceback:

Error:

Traceback:
TypeError: Cannot read properties of undefined (reading 'endsWith')
    at Class.init (http://oca-web-14-0-pr2212-0609f4056780.runboat.odoo-community.org/web/content/421-419e200/web.assets_backend.js:3258:862)
    at Class.prototype.<computed> [as init] (http://oca-web-14-0-pr2212-0609f4056780.runboat.odoo-community.org/web/content/418-8a992a2/web.assets_common.js:4646:488)
    at new Class (http://oca-web-14-0-pr2212-0609f4056780.runboat.odoo-community.org/web/content/418-8a992a2/web.assets_common.js:4647:65)
    at ComponentAdapter.willStart (http://oca-web-14-0-pr2212-0609f4056780.runboat.odoo-community.org/web/content/421-419e200/web.assets_backend.js:3042:84)
    at ComponentAdapter.__prepareAndRender (http://oca-web-14-0-pr2212-0609f4056780.runboat.odoo-community.org/web/content/418-8a992a2/web.assets_common.js:1285:70)
    at ComponentAdapter.__prepare (http://oca-web-14-0-pr2212-0609f4056780.runboat.odoo-community.org/web/content/418-8a992a2/web.assets_common.js:1278:34)
    at QWeb.eval (eval at _compile (http://oca-web-14-0-pr2212-0609f4056780.runboat.odoo-community.org/web/content/418-8a992a2/web.assets_common.js:971:178), <anonymous>:28:26)
    at QWeb.fn (http://oca-web-14-0-pr2212-0609f4056780.runboat.odoo-community.org/web/content/418-8a992a2/web.assets_common.js:955:173)
    at QWeb.render (http://oca-web-14-0-pr2212-0609f4056780.runboat.odoo-community.org/web/content/418-8a992a2/web.assets_common.js:962:20)
    at PatchableClass.__render (http://oca-web-14-0-pr2212-0609f4056780.runboat.odoo-community.org/web/content/418-8a992a2/web.assets_common.js:1289:33)

## To Reproduce

1.  Click on 'Add custom filter' in a Odoo 14 environment with the `web_advanced_search` module installed
2. Without changing the filter field select the option `is equal to` or `is not equal to` (make sure the 'default' filter field of the model you try this on is not a boolean, because then there won't be the option `is (not) equal to`)
3. Now a traceback will pop up

**Expected behavior**
The custom filter works and does not return a traceback

**Additional context**
Reproduced on the OCA Runbot

**Comment by jcchoquet** [comment]
same problem in module version 15
