### ISSUE TITLE
Problem with create CRM in mobile phone

### ISSUE THREAD

**Issue by alvarosalinero** [OCA/web#2253]
Hi,

I have a user with sales permission **Sales / User: Own Documents Only**

When I try to create an opportunity from mobile I get the following error:

Error:
```
TypeError: Cannot read properties of undefined (reading 'toggleFold')
    at Class._onCloseQuickCreate (/web/content/1235-22f4f5b/web.assets_backend.js:6302:169)
    at Class.<anonymous> (/web/content/992-b52376e/web.assets_common.js:4791:11)
    at Class.trigger (/web/content/992-b52376e/web.assets_common.js:4789:180)
    at Class._trigger_up (/web/content/992-b52376e/web.assets_common.js:4795:378)
    at Class._trigger_up (/web/content/992-b52376e/web.assets_common.js:4795:462)
    at Class.trigger_up (/web/content/992-b52376e/web.assets_common.js:4795:280)
    at Class.addQuickCreate (/web/content/1235-22f4f5b/web.assets_backend.js:2434:6)
    at Class.addQuickCreate (/web/content/1235-22f4f5b/web.assets_backend.js:6290:45)
    at http://localhost:8071/web/content/1235-22f4f5b/web.assets_backend.js:2482:368
    at async Class._removeSampleData (/web/content/1235-22f4f5b/web.assets_backend.js:1349:764)
```

That could be happening?

Thank you very much.

All the best,

Álvaro

**Comment by legalsylvain** [comment]
Hi Alvaro. Is it relatéd to OCA/web modules ?
If yes could you :
- say the modules installed
- say the version And if it's EE or CE
- reproduce the bug on runboat / runbot ? 

Thanks.

(Closing in the meantime, feel free to repopen with all the info)
