### ISSUE TITLE
[16.0] Error when uninstalling web_dark_mode

### ISSUE THREAD

**Issue by legalsylvain** [OCA/web#2402]
## Module 
OCA/16.0/web_dark_mode

## Describe the bug

- Go to the runboat
- Try to uninstall `web_dark_mode`

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1613, in _serve_ir_http
    ir_http._post_dispatch(response)
  File "/mnt/data/odoo-addons-dir/web_dark_mode/models/ir_http.py", line 21, in _post_dispatch
    cls._set_color_scheme(response)
  File "/mnt/data/odoo-addons-dir/web_dark_mode/models/ir_http.py", line 15, in _set_color_scheme
    user_scheme = "dark" if user.dark_mode else "light"
AttributeError: 'res.users' object has no attribute 'dark_mode'
```

Note : the uninstallation is done.

ref : https://github.com/OCA/web/pull/2351
CC : @fkantelberg

**Comment by vincent-hatakeyama** [comment]
Should be closed, the issue was fixed with the PR.
