### ISSUE TITLE
Web Chatter Position breaks the KB Module

### ISSUE THREAD

**Issue by nsdadmin** [OCA/web#2464]
## Module
web_chatter_position

## Describe the bug
Web chatter position module can't move the collapsed chatter when user is set to force to bottom causing an error.

## To Reproduce
**Affected versions**:

1. Install Module.
2. Set user preference to Bottom.
3. Clear browser cache.
4. Try to enter the KB Module.

**Expected behavior**
Be able to open the KB Module.

**Additional context**
```
UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:1231:101) (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:1231)
    at owl.App.handleError (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:2063:29) (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:2063)
    at Fiber._render (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:1462:19) (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:1462)
    at Fiber.render (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:1460:6) (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:1460)
    at ComponentNode.initiateRender (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:1539:47) (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:1539)

Caused by: TypeError: Cannot read properties of null (reading 'append')
    at append (https://portal.nsandd.com/web/assets/debug/web.assets_backend.js:1352:105) (https://portal.nsandd.com/web/assets/debug/web.assets_backend.js:1352)
    at KnowledgeFormCompiler.compile (https://portal.nsandd.com/web/assets/debug/web.assets_backend.js:14663:714) (https://portal.nsandd.com/web/assets/debug/web.assets_backend.js:14663)
    at compile (patch web_chatter_position) (https://portal.nsandd.com/web/assets/debug/web.assets_backend.js:1278:22) (patch web_chatter_position https://portal.nsandd.com/web/assets/debug/web.assets_backend.js:1278)
    at useViewCompiler (https://portal.nsandd.com/web/assets/debug/web.assets_backend.js:4638:172) (https://portal.nsandd.com/web/assets/debug/web.assets_backend.js:4638)
    at KnowledgeArticleFormRenderer.setup (https://portal.nsandd.com/web/assets/debug/web.assets_backend.js:3157:1376) (https://portal.nsandd.com/web/assets/debug/web.assets_backend.js:3157)
    at KnowledgeArticleFormRenderer.setup (https://portal.nsandd.com/web/assets/debug/web.assets_backend.js:13299:1191) (https://portal.nsandd.com/web/assets/debug/web.assets_backend.js:13299)
    at new ComponentNode (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:1534:202) (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:1534)
    at https://portal.nsandd.com/web/assets/debug/web.assets_common.js:2061:6 (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:2061)
    at KnowledgeArticleFormController.slot5 (eval at compile (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:2026:370), <anonymous>:68:32) (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:2026)
    at callSlot (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:1636:25) (https://portal.nsandd.com/web/assets/debug/web.assets_common.js:1636)
```

**Comment by liebana** [comment]
Can you be more specific on "KB Module"? Enterprise? OCA?

**Comment by nsdadmin** [comment]
The new Knowledge Base Module. Yes, we're in Enterprise on odoo.sh

Matthew Glennon
National Security & Door Corp.

Please use the following address for IT support related requests:
***@***.***

**Comment by BT-jmontero** [comment]
The same thing happens when trying to open a Mailing (from Email Marketing).

In my case, with debug=assets set, the key JS line is this one:

Caused by: TypeError: Cannot read properties of null (reading 'append')
    at append (http://localhost:8069/web/assets/debug/web.assets_backend.js:18700:12) (/web/static/src/core/utils/xml.js:69)
    at FormCompiler.compile (http://localhost:8069/web/assets/debug/web.assets_backend.js:237642:17) (/web_chatter_position/static/src/js/web_chatter_position.esm.js:133)

In my case, L128 returns null (sadly the div with the "o_form_sheet_bg" class is not present):
const formSheetBgXml = res.querySelector(".o_form_sheet_bg");

As a result, L133 fails:
append(formSheetBgXml, sheetBgChatterContainerHookXml);

**Comment by BT-jmontero** [comment]
In my case, I made a quick test and right after L128

const formSheetBgXml = res.querySelector(".o_form_sheet_bg");

I added an `if` statement checking for `null` and only if not null, I executed everything else, and it worked (the error is gone for Mailings and the chatter is properly moved for other records).

```
                if (formSheetBgXml != null) {
                    const sheetBgChatterContainerHookXml =
                    chatterContainerHookXml.cloneNode(true);
                    sheetBgChatterContainerHookXml.classList.add("o-isInFormSheetBg");
                    sheetBgChatterContainerHookXml.setAttribute("t-if", true);
                    append(formSheetBgXml, sheetBgChatterContainerHookXml);
                    const sheetBgChatterContainerXml =
                        sheetBgChatterContainerHookXml.querySelector("ChatterContainer");
                    sheetBgChatterContainerXml.setAttribute("isInFormSheetBg", "true");
                    chatterContainerHookXml.setAttribute("t-if", false);
                }
```

FYI @liebana

**Comment by ksignorini** [comment]
Is there a plan to fix this bug? We are also experiencing it.

**Comment by pedrobaeza** [comment]
While nobody provides the fix, no.

**Comment by andreampiovesana** [comment]
also for me

**Comment by Dg0210** [comment]
> The same thing happens when trying to open a Mailing (from Email Marketing).
> 
> In my case, with debug=assets set, the key JS line is this one:
> 
> Caused by: TypeError: Cannot read properties of null (reading 'append') at append (http://localhost:8069/web/assets/debug/web.assets_backend.js:18700:12) (/web/static/src/core/utils/xml.js:69) at FormCompiler.compile (http://localhost:8069/web/assets/debug/web.assets_backend.js:237642:17) (/web_chatter_position/static/src/js/web_chatter_position.esm.js:133)
> 
> In my case, L128 returns null (sadly the div with the "o_form_sheet_bg" class is not present): const formSheetBgXml = res.querySelector(".o_form_sheet_bg");
> 
> As a result, L133 fails: append(formSheetBgXml, sheetBgChatterContainerHookXml);

i have the same issue, did u fix it?

**Comment by BT-jmontero** [comment]
I have proposed the following PR to fix the issue: https://github.com/OCA/web/pull/2571
Let's see if and when it is accepted

**Comment by vincent-hatakeyama** [comment]
The issue should be closed as the fix is merged.
