### ISSUE TITLE
[16.0][BUG] web_responsive: OwlError: Invalid prop suffix 

### ISSUE THREAD

**Issue by Jaoabsm** [OCA/web#2474]
Good morning, I have the following problem, I installed the Responsive Web module without problem but in some modules it generates an error, even in the settings option, the biggest problem is that it doesn't let me uninstall either. HELP ME

This is the error message that appears:

UncaughtPromiseError > OwlError
Promesa desconocida > Invalid prop suffix

OwlError: Invalid prop suffix
    at CodeGenerator.formatProp (http://172.23.131.139:8069/web/assets/567-858d158/web.assets_common.min.js:1789:12)
    at http://172.23.131.139:8069/web/assets/567-858d158/web.assets_common.min.js:1791:68
    at Array.map (<anonymous>)
    at CodeGenerator.formatPropObject (http://172.23.131.139:8069/web/assets/567-858d158/web.assets_common.min.js:1791:50)
    at CodeGenerator.compileComponent (http://172.23.131.139:8069/web/assets/567-858d158/web.assets_common.min.js:1794:113)
    at CodeGenerator.compileAST (http://172.23.131.139:8069/web/assets/567-858d158/web.assets_common.min.js:1686:558)
    at CodeGenerator.compileInNewTarget (http://172.23.131.139:8069/web/assets/567-858d158/web.assets_common.min.js:1670:188)
    at CodeGenerator.compileComponent (http://172.23.131.139:8069/web/assets/567-858d158/web.assets_common.min.js:1795:133)
    at CodeGenerator.compileAST (http://172.23.131.139:8069/web/assets/567-858d158/web.assets_common.min.js:1686:558)
    at CodeGenerator.compileInNewTarget (http://172.23.131.139:8069/web/assets/567-858d158/web.assets_common.min.js:1670:188)

**Comment by pedrobaeza** [comment]
You should check if that problem is present in the runboat (pressing the "Runbot | Try me" button with admin/admin. If not, it's something specific of your installation, maybe an incompatibility with other non-official modules.
