### ISSUE TITLE
[16.0] web_refresher: bug when clicking on production plan

### ISSUE THREAD

**Issue by micheledic** [OCA/web#2898]
## Module
web_refresher

## Describe the bug
When clicking on production plan schedulethere is this error:
```
UncaughtPromiseError > OwlError
Promise non rilevata > Cannot find the definition of component "Refresher"
OwlError: Cannot find the definition of component "Refresher"
Error: Cannot find the definition of component "Refresher"
at https://xxxx/web/assets/705996-469e291/web.assets_common.min.js:2095:33
at MrpMpsControlPanel.template (eval at compile (https://xxxxx/web/assets/705996-469e291/web.assets_common.min.js:2057:374), <anonymous>:103:15)
at MrpMpsControlPanel.template (eval at compile (https://xxxx/web/assets/705996-469e291/web.assets_common.min.js:2057:374), <anonymous>:18:27)
at Fiber._render (https://xx/web/assets/705996-469e291/web.assets_common.min.js:1496:96)
at Fiber.render (https://xxx/web/assets/705996-469e291/web.assets_common.min.js:1495:6)
at ComponentNode.initiateRender (https://xxx/web/assets/705996-469e291/web.assets_common.min.js:1563:47)
```
## To Reproduce

1. Click on MRP=>PRODUCTION=>PRODUCTION SCHEDULE
2.
3.

**Comment by TesaLazarenko** [comment]
Hi, I'll check it out in the next few days

**Comment by TesaLazarenko** [comment]
PR 16.0: https://github.com/OCA/web/pull/2913
PR 17.0: https://github.com/OCA/web/pull/2914

**Comment by TesaLazarenko** [comment]
@micheledic done
