### ISSUE TITLE
[17.0] web_m2x_options error when opening hr.skill.type

### ISSUE THREAD

**Issue by Paulius11** [OCA/web#2934]
Module: hr (Human Resources)
Describe the bug

Developer mode needs to be activated.

An error occurs when trying to access the "hr.skill.type" view in Odoo. The error message indicates that the code is trying to access a property ("kanban") of an undefined variable.
To Reproduce

Affected versions: 17.0

    Navigate to the Human Resources module in Odoo.
    Try to access the "Skill Types" view (usually under "Configuration").
    The error should appear.

Expected behavior
The "Skill Types" view should load and display a list of skill types.

```
UncaughtPromiseError > TypeError

Uncaught Promise > Cannot read properties of undefined (reading 'kanban')

TypeError: Cannot read properties of undefined (reading 'kanban')

    at FormController._setSubViewLimit (https://odoo.com/web/assets/04b5dff/web.assets_web.min.js:7605:39)

    at FormController.setup (https://odoo..com/web/assets/04b5dff/web.assets_web.min.js:7600:92)

    at FormController.setup (https://odoo..com/web/assets/04b5dff/web.assets_web.min.js:12859:446)

    at new ComponentNode (https://odoo..com/web/assets/04b5dff/web.assets_web.min.js:1002:202)

    at https://odoo..com/web/assets/04b5dff/web.assets_web.min.js:1540:6

    at View.slot1 (eval at compile (https://odoo..com/web/assets/04b5dff/web.assets_web.min.js:1500:374), <anonymous>:13:36)

    at callSlot (https://odoo..com/web/assets/04b5dff/web.assets_web.min.js:1109:25)

    at WithSearch.template (eval at compile (https://odoo..com/web/assets/04b5dff/web.assets_web.min.js:1500:374), <anonymous>:8:12)

    at Fiber._render (https://odoo..com/web/assets/04b5dff/web.assets_web.min.js:940:96)

    at Fiber.render (https://odoo..com/web/assets/04b5dff/web.assets_web.min.js:939:6)
 ```

**Comment by Paulius11** [comment]
Also error is triggered only when developer mode is activated and I go to: Time Off -> Management- Time Off

`UncaughtPromiseError > OwlError
Uncaught Promise > Invalid props for component 'ListMany2ManyTagsAvatarField': unknown key 'fieldColor', unknown key 'fieldColorOptions'
OwlError: Invalid props for component 'ListMany2ManyTagsAvatarField': unknown key 'fieldColor', unknown key 'fieldColorOptions'
    at Object.validateProps (http://localhost:8017/web/assets/9812b32/web.assets_web.min.js:1142:67)
    at Field.template (eval at compile (http://localhost:8017/web/assets/9812b32/web.assets_web.min.js:1501:374), <anonymous>:17:13)
    at Fiber._render (http://localhost:8017/web/assets/9812b32/web.assets_web.min.js:940:96)
    at Fiber.render (http://localhost:8017/web/assets/9812b32/web.assets_web.min.js:939:6)
    at ComponentNode.initiateRender (http://localhost:8017/web/assets/9812b32/web.assets_web.min.js:1007:47)`

**Comment by JordiMForgeFlow** [comment]
Hi @Paulius11 

Could you test this fix: https://github.com/OCA/web/pull/2957?

**Comment by Paulius11** [comment]
Hello @JordiMForgeFlow 

With developer mode enabled, when I navigate to Time Off -> Management -> Time Off, I encounter the following error:


```UncaughtPromiseError > OwlError
Uncaught Promise > Invalid props for component 'ListMany2ManyTagsAvatarField': unknown key 'fieldColor', unknown key 'fieldColorOptions'
OwlError: Invalid props for component 'ListMany2ManyTagsAvatarField': unknown key 'fieldColor', unknown key 'fieldColorOptions'
    at Object.validateProps (http://localhost:8017/web/assets/77f4d9e/web.assets_web.min.js:1142:67)
    at Field.template (eval at compile (http://localhost:8017/web/assets/77f4d9e/web.assets_web.min.js:1501:374), <anonymous>:17:13)
    at Fiber._render (http://localhost:8017/web/assets/77f4d9e/web.assets_web.min.js:940:96)
    at Fiber.render (http://localhost:8017/web/assets/77f4d9e/web.assets_web.min.js:939:6)
    at ComponentNode.initiateRender (http://localhost:8017/web/assets/77f4d9e/web.assets_web.min.js:1007:47)```

**Comment by JordiMForgeFlow** [comment]
@Paulius11 could you try now? I have added some corrections

**Comment by Paulius11** [comment]
@JordiMForgeFlow It's working now, thanks for the quick fix!

**Comment by Paulius11** [comment]
@JordiMForgeFlow 
Found one more place where exception is raised:
In Project -> Tasks -> My Tasks

```
UncaughtPromiseError > OwlError
Uncaught Promise > Invalid props for component 'KanbanMany2ManyTagsAvatarUserField': unknown key 'fieldColor', unknown key 'fieldColorOptions'
OwlError: Invalid props for component 'KanbanMany2ManyTagsAvatarUserField': unknown key 'fieldColor', unknown key 'fieldColorOptions'
    Error: Invalid props for component 'KanbanMany2ManyTagsAvatarUserField': unknown key 'fieldColor', unknown key 'fieldColorOptions'
        at Object.validateProps (http://localhost:8017/web/assets/a550918/web.assets_web.min.js:1141:67)
        at Field.template (eval at compile (http://localhost:8017/web/assets/a550918/web.assets_web.min.js:1502:374), <anonymous>:17:13)
        at Fiber._render (http://localhost:8017/web/assets/a550918/web.assets_web.min.js:940:96)
        at Fiber.render (http://localhost:8017/web/assets/a550918/web.assets_web.min.js:939:6)
        at ComponentNode.initiateRender (http://localhost:8017/web/assets/a550918/web.assets_web.min.js:1007:47)
```

**Comment by JordiMForgeFlow** [comment]
@Paulius11 should be fixed by https://github.com/OCA/web/pull/2959

**Comment by Paulius11** [comment]
@JordiMForgeFlow Yes, it's fixed now. Thanks!

**Comment by eefahd** [comment]
@JordiMForgeFlow  it seems the same issue appears when opening Point of Sale:
`UncaughtPromiseError > OwlError

Uncaught Promise > Invalid props for component 'KanbanMany2OneAvatarUserField': unknown key 'fieldColor', unknown key 'fieldColorOptions'`
