### ISSUE TITLE
[10.0] web_export_view error when trying to migrate to v10

### ISSUE THREAD

**Issue by augustosamame** [OCA/web#479]
Hi. I am trying to migrate this module to version 10.

I have followed the migration instructions in the OCA wiki here:

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

However, upon installing the module I get the following error:

```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/module/module.py", line 527, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo-10.0/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 177, in load_module_graph
    env['ir.ui.view']._validate_module_views(module_name)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 1180, in _validate_module_views
    self.raise_view_error("Can't validate view:\n%s" % (e.message or repr(e)), vid)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_ui_view.py", line 454, in raise_view_error
    raise ValueError(message)
ValueError: Can't validate view:
El campo `first_invoice_date` no existe

Error de contexto:
Vista `Invoice Order`
[view_id: 701, xml_id: sale_multiple_invoice_v10.view_sale_advance_payment_inv, model: sale.advance.payment.inv, parent_id: 501]

Error de contexto:
Vista `Invoice Order`
[view_id: 701, xml_id: sale_multiple_invoice_v10.view_sale_advance_payment_inv, model: sale.advance.payment.inv, parent_id: 501]
```

There is no reference to the first_invoice_date field in the code.
I am a newbie at Odoo.
Any help would be appreciated.

**Comment by pedrobaeza** [comment]
That migration guide is only for starting correctly. Then, you need to do the rest of the work of the migration itself. Anyway, this module has been already migrated here: https://github.com/OCA/web/pull/444
