### ISSUE TITLE
web_export_view - 'tmp is not defined'

### ISSUE THREAD

**Issue by RaffaeleT** [OCA/web#516]
I am getting this error when exporting a tree view, on an Odoo 9 on Ubuntu 14.04.
The tree contains:

- a date field
- some char fields
- one integer field
- three float fields with float_time widget
I tried removing the float fields but the error persists.

`Uncaught ReferenceError: tmp is not defined
http://sydev9:8069/web/content/525-0bf94ad/web.assets_backend.js:6545
Traceback:
ReferenceError: tmp is not defined
    at String.<anonymous> (http://sydev9:8069/web/content/525-0bf94ad/web.assets_backend.js:6545:79)
    at Function.each (http://sydev9:8069/web/content/503-be3e7a8/web.assets_common.js:473:767)
    at HTMLTableRowElement.<anonymous> (http://sydev9:8069/web/content/525-0bf94ad/web.assets_backend.js:6542:142)
    at Function.each (http://sydev9:8069/web/content/503-be3e7a8/web.assets_common.js:473:767)
    at Class.on_sidebar_export_view_xls (http://sydev9:8069/web/content/525-0bf94ad/web.assets_backend.js:6541:259)
    at HTMLAnchorElement.<anonymous> (http://sydev9:8069/web/content/525-0bf94ad/web.assets_backend.js:3341:1095)
    at HTMLDivElement.dispatch (http://sydev9:8069/web/content/503-be3e7a8/web.assets_common.js:740:451)
    at HTMLDivElement.elemData.handle (http://sydev9:8069/web/content/503-be3e7a8/web.assets_common.js:713:173)`

**Comment by pedrobaeza** [comment]
Please update your module. It was fixed yesterday.

**Comment by RaffaeleT** [comment]
Hallo thank you.
I pulled and installed the module today, so I assume it is the latest version available (9.0.1.0.1)
The error above results from Chrome.
For reference sake, in IE11 it gives:
`Variable undefined in strict mode
http://sydev9:8069/web/content/525-0bf94ad/web.assets_backend.js:6545
Traceback:
ReferenceError: Variable undefined in strict mode
   at Anonymous function (http://sydev9:8069/web/content/525-0bf94ad/web.assets_backend.js:6545:76)
   at each (http://sydev9:8069/web/content/503-be3e7a8/web.assets_common.js:473:752)
   at Anonymous function (http://sydev9:8069/web/content/525-0bf94ad/web.assets_backend.js:6542:140)
   at each (http://sydev9:8069/web/content/503-be3e7a8/web.assets_common.js:473:752)
   at on_sidebar_export_view_xls (http://sydev9:8069/web/content/525-0bf94ad/web.assets_backend.js:6541:257)
   at Anonymous function (http://sydev9:8069/web/content/525-0bf94ad/web.assets_backend.js:3341:1081)
   at jQuery.event.dispatch (http://sydev9:8069/web/content/503-be3e7a8/web.assets_common.js:740:372)
   at elemData.handle (http://sydev9:8069/web/content/503-be3e7a8/web.assets_common.js:713:76)
`

**Comment by NothingCtrl** [comment]
@pedrobaeza I'm on laster version v9. The export error when tree view has field `interger`, I can bypass the error by using widget="char"
```
http://localhost:8069/web_export_view/static/src/js/web_export_view.js:95
Traceback:
ReferenceError: tmp is not defined
    at String.<anonymous> (http://localhost:8069/web_export_view/static/src/js/web_export_view.js:95:41)
    at Function.each (http://localhost:8069/web/static/lib/jquery/jquery.js:383:58)
    at HTMLTableRowElement.<anonymous> (http://localhost:8069/web_export_view/static/src/js/web_export_view.js:77:27)
    at Function.each (http://localhost:8069/web/static/lib/jquery/jquery.js:383:58)
    at Class.on_sidebar_export_view_xls (http://localhost:8069/web_export_view/static/src/js/web_export_view.js:70:15)
    at HTMLLIElement.dispatch (http://localhost:8069/web/static/lib/jquery/jquery.js:4641:58)
    at HTMLLIElement.elemData.handle (http://localhost:8069/web/static/lib/jquery/jquery.js:4309:63)
```

**Comment by pedrobaeza** [comment]
Well, it was fixed, so please try the same on runbot, and if you reproduce it, then it should be something new.
