### ISSUE TITLE
Web Crush after installing web_responsive

### ISSUE THREAD

**Issue by samichege** [OCA/web#542]
Completely unable to load the web interface after installing this module. How do i uninstall this module on the command Prompt?

2017-01-25 10:16:54,859 19870 INFO 19011 werkzeug: 41.75.79.4 - - [25/Jan/2017 10:16:54] "POST /web/dataset/call_kw/ir.config_parameter/get_param HTTP/1.1" 200 -
2017-01-25 10:16:55,933 19870 INFO 19011 odoo.addons.base.module.module: Downloading module `web_responsive` from OpenERP Apps
2017-01-25 10:16:55,995 19870 INFO 19011 odoo.addons.base.module.module: Copy downloaded module `web_responsive` to `/opt/odoo/.local/share/Odoo/addons/10.0/web_responsive`
2017-01-25 10:16:56,861 19870 INFO 19011 odoo.modules.loading: loading 1 modules...
2017-01-25 10:16:56,886 19870 INFO 19011 odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries
2017-01-25 10:16:57,042 19870 INFO 19011 odoo.modules.loading: loading 157 modules...
2017-01-25 10:16:57,263 19870 INFO 19011 odoo.modules.loading: 157 modules loaded in 0.22s, 0 queries
2017-01-25 10:16:57,269 19870 INFO 19011 odoo.modules.loading: loading 158 modules...
2017-01-25 10:16:57,548 19870 INFO 19011 odoo.modules.registry: module web_responsive: creating or updating database tables
2017-01-25 10:16:57,626 19870 INFO 19011 odoo.modules.loading: loading web_responsive/views/assets.xml
2017-01-25 10:16:57,737 19870 INFO 19011 odoo.modules.loading: loading web_responsive/views/web.xml
2017-01-25 10:16:57,880 19870 INFO 19011 odoo.addons.base.ir.ir_translation: module web_responsive: no translation for language fr
2017-01-25 10:16:57,921 19870 INFO 19011 odoo.addons.base.ir.ir_ui_view: Element '<xpath expr="//nav[@id='oe_main_menu_navbar']">' cannot be located in parent view

Error context:
View `App Drawer - Web Client`
[view_id: 1931, xml_id: web_responsive.webclient_bootstrap, model: n/a, parent_id: 173]
2017-01-25 10:16:57,924 19870 INFO 19011 odoo.addons.base.ir.ir_ui_view: Can't validate view:
Element '<xpath expr="//nav[@id='oe_main_menu_navbar']">' cannot be located in parent view

Error context:
View `App Drawer - Web Client`
[view_id: 1931, xml_id: web_responsive.webclient_bootstrap, model: n/a, parent_id: 173]

Error context:
View `App Drawer - Web Client`
[view_id: 1931, xml_id: web_responsive.webclient_bootstrap, model: n/a, parent_id: 173]
2017-01-25 10:16:57,925 19870 ERROR 19011 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 177, in load_module_graph
    env['ir.ui.view']._validate_module_views(module_name)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1180, in _validate_module_views
    self.raise_view_error("Can't validate view:\n%s" % (e.message or repr(e)), vid)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 454, in raise_view_error
    raise ValueError(message)
ValueError: Can't validate view:
Element '<xpath expr="//nav[@id='oe_main_menu_navbar']">' cannot be located in parent view

Error context:
View `App Drawer - Web Client`
[view_id: 1931, xml_id: web_responsive.webclient_bootstrap, model: n/a, parent_id: 173]

Error context:
View `App Drawer - Web Client`
[view_id: 1931, xml_id: web_responsive.webclient_bootstrap, model: n/a, parent_id: 173]
2017-01-25 10:16:57,926 19870 ERROR 19011 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 709, in install_from_urls
    post_install_action = to_install.button_immediate_install()
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 177, in load_module_graph
    env['ir.ui.view']._validate_module_views(module_name)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1180, in _validate_module_views
    self.raise_view_error("Can't validate view:\n%s" % (e.message or repr(e)), vid)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 454, in raise_view_error
    raise ValueError(message)
ValueError: Can't validate view:
Element '<xpath expr="//nav[@id='oe_main_menu_navbar']">' cannot be located in parent view

Error context:
View `App Drawer - Web Client`
[view_id: 1931, xml_id: web_responsive.webclient_bootstrap, model: n/a, parent_id: 173]

**Comment by pedrobaeza** [comment]
Sorry, but the problem is in your side. Maybe other conflictive module, or not service restarted/module updated. If you reproduce the problem in runbot, then put it here.

**Comment by samichege** [comment]
Most Probably So.

How do i uninstall the Module in command prompt?

Sami


On 1 Feb 2017, at 6:46 PM, Pedro M. Baeza <notifications@github.com> wrote:

Sorry, but the problem is in your side. Maybe other conflictive module, or not service restarted/module updated. If you reproduce the problem in runbot, then put it here.

**Comment by pedrobaeza** [comment]
That's not possible. Odoo doesn't offer that possibility. You can change the state of the module to "to uninstall" via DB and restart to try.

**Comment by samichege** [comment]
Thanx for you prompt response guys. Very much appreciated.

Kindly, give me a guide on how to change the state of the module to "to uninstall" via DB.

Please.



On 1 Feb 2017, at 6:53 PM, Pedro M. Baeza <notifications@github.com> wrote:

That's not possible. Odoo doesn't offer that possibility. You can change the state of the module to "to uninstall" via DB and restart to try.

**Comment by pedrobaeza** [comment]
Sorry, that's out of scope of this. You should contact an Odoo integrator if you are not able to do it on your own.

**Comment by samichege** [comment]
Thanx Team.

Very much appreciated.

Sami - Over and Out




On 1 Feb 2017, at 7:02 PM, Pedro M. Baeza <notifications@github.com> wrote:

Sorry, that's out of scope of this. You should contact an Odoo integrator if you are not able to do it on your own.
