### ISSUE TITLE
[10.0] web_export_view: Uncaught error

### ISSUE THREAD

**Issue by qtheuret** [OCA/web#551]
After installing 'web_export_view' module, when I go to a list view, I have this error : 

Uncaught Error: QWeb2: Template 'WebExportTreeViewXls' not found

http://localhost:20069/web/content/251-bd08794/web.assets_common.js:2908
Traceback:
Error: QWeb2: Template 'WebExportTreeViewXls' not found
    at Object.exception (http://localhost:20069/web/content/251-bd08794/web.assets_common.js:2908:7)
    at Engine._render (http://localhost:20069/web/content/251-bd08794/web.assets_common.js:2952:103)
    at Engine.render (http://localhost:20069/web/content/251-bd08794/web.assets_common.js:2948:151)
    at Class.redraw (http://localhost:20069/web/content/282-05eb3e0/web.assets_backend.js:3922:349)
    at Class.redraw (http://localhost:20069/web/content/251-bd08794/web.assets_common.js:3012:371)
    at Class.add_items (http://localhost:20069/web/content/282-05eb3e0/web.assets_backend.js:1931:626)
    at http://localhost:20069/web/content/282-05eb3e0/web.assets_backend.js:1931:850
    at Function._.each._.forEach (http://localhost:20069/web/content/251-bd08794/web.assets_common.js:12:558)
    at Class.add_toolbar (http://localhost:20069/web/content/282-05eb3e0/web.assets_backend.js:1931:684)
    at Class.render_sidebar (http://localhost:20069/web/content/282-05eb3e0/web.assets_backend.js:2024:479)

**Comment by eLBati** [comment]
Hello @qtheuret , just tried on runbot http://3279665-10-0-c23684.runbot1.odoo-community.org to export invoice list and got no error.
Did you do any particular step/configuration?

**Comment by qtheuret** [comment]
My bad, it seems that there is a non-compatibility between the web_export_view module and a backend module I downloaded on apps.odoo.com.
I close this issue.

**Comment by jmawad-bobbies** [comment]
Hi,

Actually this module breaks the enterprise edition (10.0).

Is this module compatible with Odoo 10 Enterprise?

![capture d ecran 2017-04-20 a 14 27 36](https://cloud.githubusercontent.com/assets/11539032/25230782/9bf524a2-25d5-11e7-9ae5-658455c0faf5.png)

**Comment by alfaser123** [comment]
I got the same problem when install in other folder different to /addons/  i use to install for testing in /addons_testing.  The issues is solved after install in /addons/ folder

Hope it helps

**Comment by zeroheure** [comment]
I've had the same error here, and solved it. Config is : 
Odoo 10 CE nightly build, ecommerce setup with various related modules, addons in /var/lib/addons/ folder.
Restarting Odoo and reloaded one or more time the web page solve the problem.
