### ISSUE TITLE
Uncaught Error: QWeb2: Template 'WebExportTreeViewXls' not found

### ISSUE THREAD

**Issue by ispottahiti** [OCA/web#568]
Hi, I have this err comming out : Uncaught Error: QWeb2: Template 'WebExportTreeViewXls' not found
Module is not installed so i can not remove, Odoo version 10
http://78.46.242.162/web/content/251-6fb7904/web.assets_common.js:2908
Retraçage :
Error: QWeb2: Template 'WebExportTreeViewXls' not found
    at Object.exception (http://78.46.242.162/web/content/251-6fb7904/web.assets_common.js:2908:7)
    at Engine._render (http://78.46.242.162/web/content/251-6fb7904/web.assets_common.js:2952:103)
    at Engine.render (http://78.46.242.162/web/content/251-6fb7904/web.assets_common.js:2948:151)
    at Class.redraw (http://78.46.242.162/web/content/1224-a88b7ad/web.assets_backend.js:3965:349)
    at Class.redraw (http://78.46.242.162/web/content/251-6fb7904/web.assets_common.js:3012:371)
    at Class.add_items (http://78.46.242.162/web/content/1224-a88b7ad/web.assets_backend.js:1928:530)
    at http://78.46.242.162/web/content/1224-a88b7ad/web.assets_backend.js:1928:754
    at Function._.each._.forEach (http://78.46.242.162/web/content/251-6fb7904/web.assets_common.js:12:558)
    at Class.add_toolbar (http://78.46.242.162/web/content/1224-a88b7ad/web.assets_backend.js:1928:588)
    at Class.render_sidebar (http://78.46.242.162/web/content/1224-a88b7ad/web.assets_backend.js:2021:480)

**Comment by pedrobaeza** [comment]
No reproducible on runbot, so I close.

**Comment by aleksandar-irvas** [comment]
I have the same issue. @ispottahiti have you solve it?
