### ISSUE TITLE
Problem with odoo.http.request in unit tests / travis

### ISSUE THREAD

**Issue by tarteo** [OCA/web#583]
I don't know where to report this kind of issue.
I've made unit tests for a web controller that work on my local (and other) machine but fails when ran by Travis. It throws _RuntimeError 'Object unbound'_ whenever I try to use request.env

```
2017-03-13 13:51:48,518 5326 INFO openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: test_controller (odoo.addons.web_chatter_paste.tests.test_web_chatter_paste.TestWebChatterPaste)
2017-03-13 13:51:48,533 5326 ERROR openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: ERROR
2017-03-13 13:51:48,535 5326 INFO openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: ======================================================================
2017-03-13 13:51:48,536 5326 ERROR openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: ERROR: test_controller (odoo.addons.web_chatter_paste.tests.test_web_chatter_paste.TestWebChatterPaste)
2017-03-13 13:51:48,536 5326 ERROR openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: Traceback (most recent call last):
2017-03-13 13:51:48,537 5326 ERROR openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: `   File "/home/travis/build/OCA/web/web_chatter_paste/tests/test_web_chatter_paste.py", line 14, in test_controller
2017-03-13 13:51:48,537 5326 ERROR openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: `     attachment_obj = self.env['ir.attachment'].with_env(request.env)
2017-03-13 13:51:48,538 5326 ERROR openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: `   File "/home/travis/.local/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
2017-03-13 13:51:48,538 5326 ERROR openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: `     return getattr(self._get_current_object(), name)
2017-03-13 13:51:48,539 5326 ERROR openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: `   File "/home/travis/.local/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
2017-03-13 13:51:48,539 5326 ERROR openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: `     return self.__local()
2017-03-13 13:51:48,540 5326 ERROR openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: `   File "/home/travis/.local/lib/python2.7/site-packages/werkzeug/local.py", line 135, in _lookup
2017-03-13 13:51:48,540 5326 ERROR openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: `     raise RuntimeError('object unbound')
2017-03-13 13:51:48,540 5326 ERROR openerp_test odoo.addons.web_chatter_paste.tests.test_web_chatter_paste: ` RuntimeError: object unbound

```

Problem occurs in https://github.com/OCA/web/pull/548 and https://github.com/OCA/website/pull/317

Does anyone have an idea on what the problem may be?

**Comment by pedrobaeza** [comment]
@Yajo @lasley can you help?

**Comment by hbrunn** [comment]
the problem is that this global variable is only instantiated in a request context. So either assign a mock object for the tests, or run it within a request: https://github.com/OCA/OCB/blob/10.0/odoo/tests/common.py#L232

**Comment by yajo** [comment]
Yeah, check this out too: https://github.com/odoo/odoo/pull/13902

**Comment by tarteo** [comment]
Thanks @hbrunn and @Yajo !
