### ISSUE TITLE
[9.0] web_advanced_search_x2x: When returns from selection popup it gives me an error

### ISSUE THREAD

**Issue by mibarraOdoo** [OCA/web#616]
Hi,

I'm in advanced search using a many2many field with the search type "is in the selection". In the pop up window i apply a search criterion with OR for several values. For example: Cod=4 or Cod=5 or Cod=6.

![image](https://cloud.githubusercontent.com/assets/28403674/25719097/afbce8f8-30de-11e7-8d4f-8a0165ae6e01.png)

When I apply that filter in the selection popup I have no problem, but when I select all the records and return to the previous screen with Select button,
I get the following error in odoo:

```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 828, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 849, in do_search_read
    request.context)
  File "/opt/odoo/odoo/openerp/http.py", line 1069, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 5273, in search_read
    record_ids = self.search(cr, uid, domain or [], offset=offset, limit=limit, order=order, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom_addons/partner_relations/model/res_partner.py", line 299, in search
    limit=limit, order=order, context=context, count=count)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 1658, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/res/res_partner.py", line 622, in _search
    count=count, access_rights_uid=access_rights_uid)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 4776, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 4547, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/opt/odoo/odoo/openerp/osv/expression.py", line 641, in __init__
    self.expression = distribute_not(normalize_domain(exp))
  File "/opt/odoo/odoo/openerp/osv/expression.py", line 290, in distribute_not
    elif token in DOMAIN_OPERATORS_NEGATION:
TypeError: unhashable type: 'list'
```

Any idea of what may be happening ?, 
Many thanks and apologies for my English,
Regards

**Comment by pedrobaeza** [comment]
We need this to be reproducible on OCA runbot

**Comment by pedrobaeza** [comment]
Closing as no answer
