### ISSUE TITLE
Custom shortcut icon

### ISSUE THREAD

**Issue by DeepenDev** [OCA/web#629]
Traceback (most recent call last):
  File "/ / -server/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/ / -server/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/ / -server/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/ / -server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/ / -server/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/ / -server/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/ / -server/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/ / -server/addons/web/controllers/main.py", line 892, in call_button
    action = self._call_kw(model, method, args, {})
  File "/ / -server/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/ / -server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/ / -server/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/ / -server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/ / -server/openerp/addons/base/module/module.py", line 534, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/ / -server/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/ / -server/openerp/modules/loading.py", line 340, in load_modules
    loaded_modules, update_module)
  File "/ / -server/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/ / -server/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/ / -server/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/ / -server/addons/stock_scanner/load_scenario.py", line 233, in scenario_convert_file
    kind=kind, report=report, pathname=pathname)
  File "/ / -server/openerp/tools/convert.py", line 849, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/ / -server/openerp/tools/convert.py", line 932, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/ / -server/openerp/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/ / -server/openerp/tools/convert.py", line 802, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/ / -server/openerp/tools/convert.py", line 775, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/ / -server/openerp/tools/convert.py", line 705, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/ / -server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/ / -server/openerp/addons/base/ir/ir_model.py", line 1163, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/ / -server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/ / -server/openerp/addons/base/ir/ir_ui_view.py", line 360, in create
    context=context)
  File "/ / -server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/ / -server/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/ / -server/openerp/models.py", line 4174, in create
    record = self.browse(self._create(old_vals))
  File "/ / -server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/ / -server/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/ / -server/openerp/models.py", line 4371, in _create
    recs._validate_fields(vals)
  File "/ / -server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/ / -server/openerp/models.py", line 1281, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

D\xe9tails de l'erreur :
L'\xe9l\xe9ment '<xpath expr="//link[@rel='shortcut icon']">' ne peut \xeatre localis\xe9 dans la vue parente

Contexte de l'erreur :
Vue `web_debranding.web_layout`
[view_id: 2437, xml_id: web_debranding.web_layout, model: n/a, parent_id: 161]
None" while parsing None:4, near
<data inherit_id="web.layout">
            <xpath expr="//link[@rel='shortcut icon']" position="replace">
                <link rel="icon" href="/web_favicon/favicon"/>
            </xpath>
        </data>

**Comment by pedrobaeza** [comment]
The problem is in your custom module web_debranding.
