### ISSUE TITLE
[9.0] web_widget_float_formula: Tests are failing

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/web#637]
There's an error on the tests for this module:
```
2017-05-22 11:25:24,069 6075 INFO openerp_test openerp.tests.common: phantomjs: loaded http://127.0.0.1:8069/web/tests?module=web_widget_float_formula success
2017-05-22 11:25:24,088 6075 INFO openerp_test werkzeug: 127.0.0.1 - - [22/May/2017 11:25:24] "POST /web/dataset/call_kw/ir.config_parameter/get_param HTTP/1.1" 200 -
2017-05-22 11:25:24,092 6075 INFO openerp_test openerp.tests.common: phantomjs: PhantomTest.run: wait for condition: window
2017-05-22 11:25:24,095 6075 INFO openerp_test werkzeug: 127.0.0.1 - - [22/May/2017 11:25:24] "POST /web/dataset/call_kw/ir.config_parameter/get_param HTTP/1.1" 200 -
2017-05-22 11:25:24,350 6075 INFO openerp_test openerp.service.common: successful login from 'admin' using database 'openerp_test'
2017-05-22 11:25:24,356 6075 INFO openerp_test openerp.tests.common: phantomjs: page.evaluate eval expr: window
2017-05-22 11:25:24,369 6075 INFO openerp_test openerp.tests.common: phantomjs: page.evaluate eval result: true
2017-05-22 11:25:24,377 6075 INFO openerp_test werkzeug: 127.0.0.1 - - [22/May/2017 11:25:24] "POST /web/dataset/call HTTP/1.1" 200 -
2017-05-22 11:25:24,379 6075 INFO openerp_test openerp.tests.common: phantomjs: PhantomTest.run: condition statified, executing: true
2017-05-22 11:25:24,391 6075 INFO openerp_test werkzeug: 127.0.0.1 - - [22/May/2017 11:25:24] "POST /web/webclient/translations HTTP/1.1" 200 -
2017-05-22 11:25:24,404 6075 INFO openerp_test werkzeug: 127.0.0.1 - - [22/May/2017 11:25:24] "POST /web/session/get_session_info HTTP/1.1" 200 -
2017-05-22 11:25:24,405 6075 INFO openerp_test openerp.tests.common: phantomjs: PhantomTest.run: execution launched, waiting for console.log('ok')...
2017-05-22 11:25:24,505 6075 INFO openerp_test werkzeug: 127.0.0.1 - - [22/May/2017 11:25:24] "GET /web/webclient/qweb HTTP/1.1" 200 -
2017-05-22 11:25:24,606 6075 INFO openerp_test werkzeug: 127.0.0.1 - - [22/May/2017 11:25:24] "POST /web/proxy/load HTTP/1.1" 200 -
2017-05-22 11:25:24,609 6075 INFO openerp_test openerp.tests.common: phantomjs: global failure in section  failed: SyntaxError: Unexpected token ','
2017-05-22 11:25:24,609 6075 INFO openerp_test openerp.tests.common: phantomjs:  failed: 1 tests out of 1 .
2017-05-22 11:25:25,284 6075 INFO openerp_test openerp.tests.common: phantomjs: web_widget_float_formula passed 18 tests.
2017-05-22 11:25:25,294 6075 ERROR openerp_test openerp.tests.common: phantomjs: error
2017-05-22 11:25:25,305 6075 INFO openerp_test openerp.tests.common: phantom_run execution finished
2017-05-22 11:25:25,306 6075 ERROR openerp_test openerp.addons.web_widget_float_formula.tests.test_js: FAIL
2017-05-22 11:25:25,309 6075 INFO openerp_test openerp.addons.web_widget_float_formula.tests.test_js: ======================================================================
2017-05-22 11:25:25,309 6075 ERROR openerp_test openerp.addons.web_widget_float_formula.tests.test_js: FAIL: test_js (openerp.addons.web_widget_float_formula.tests.test_js.TestJS)
2017-05-22 11:25:25,309 6075 ERROR openerp_test openerp.addons.web_widget_float_formula.tests.test_js: Traceback (most recent call last):
2017-05-22 11:25:25,309 6075 ERROR openerp_test openerp.addons.web_widget_float_formula.tests.test_js: `   File "/home/travis/build/OCA/web/web_widget_float_formula/tests/test_js.py", line 14, in test_js
2017-05-22 11:25:25,309 6075 ERROR openerp_test openerp.addons.web_widget_float_formula.tests.test_js: `     login="admin",
2017-05-22 11:25:25,309 6075 ERROR openerp_test openerp.addons.web_widget_float_formula.tests.test_js: `   File "/home/travis/odoo-9.0/openerp/tests/common.py", line 441, in phantom_js
2017-05-22 11:25:25,309 6075 ERROR openerp_test openerp.addons.web_widget_float_formula.tests.test_js: `     self.phantom_run(cmd, timeout)
2017-05-22 11:25:25,309 6075 ERROR openerp_test openerp.addons.web_widget_float_formula.tests.test_js: `   File "/home/travis/odoo-9.0/openerp/tests/common.py", line 393, in phantom_run
2017-05-22 11:25:25,309 6075 ERROR openerp_test openerp.addons.web_widget_float_formula.tests.test_js: `     "PhantomJS test completed without reporting success; "
2017-05-22 11:25:25,310 6075 ERROR openerp_test openerp.addons.web_widget_float_formula.tests.test_js: ` AssertionError: None is not true : PhantomJS test completed without reporting success; the log may contain errors or hints.
2017-05-22 11:25:25,310 6075 INFO openerp_test openerp.addons.web_widget_float_formula.tests.test_js: Ran 1 test in 2.704s
2017-05-22 11:25:25,310 6075 ERROR openerp_test openerp.addons.web_widget_float_formula.tests.test_js: FAILED
2017-05-22 11:25:25,310 6075 INFO openerp_test openerp.addons.web_widget_float_formula.tests.test_js:  (failures=1)
2017-05-22 11:25:25,310 6075 ERROR openerp_test openerp.modules.module: Module web_widget_float_formula: 1 failures, 0 errors
```

@obulkin you were the last one that modifies this module. Can you please check?

**Comment by obulkin** [comment]
Sure thing. I'll take a look at this when I get a chance.

**Comment by pedrobaeza** [comment]
@obulkin @lasley please fix the branch that is red a lot of time.

**Comment by lasley** [comment]
Hmmm they look to be passing in the browser, so it's gotta be something with the test runner.
