### ISSUE TITLE
Unable to uninstall, get an error

### ISSUE THREAD

**Issue by lapagept** [OCA/web#65]
```
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/openerp/http.py", line 539, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/openerp/http.py", line 292, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/openerp/http.py", line 755, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/openerp/http.py", line 388, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/openerp/addons/base/module/wizard/base_module_upgrade.py", line 105, in upgrade_module
    openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo/openerp/modules/registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/openerp/modules/loading.py", line 431, in load_modules
    registry['ir.module.module'].module_uninstall(cr, SUPERUSER_ID, modules_to_remove.values())
  File "/home/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/openerp/addons/base/module/module.py", line 462, in module_uninstall
    ir_model_data._module_data_uninstall(cr, uid, modules_to_remove, context)
  File "/home/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/openerp/addons/base/ir/ir_model.py", line 1207, in _module_data_uninstall
    ir_model_constraint._module_data_uninstall(cr, uid, constraint_ids, context)
  File "/home/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/openerp/addons/base/ir/ir_model.py", line 577, in _module_data_uninstall
    model_obj = self.pool[model]
  File "/home/odoo/openerp/modules/registry.py", line 101, in __getitem__
    return self.models[model_name]
KeyError: u'web.shortcut'
```

**Comment by yvaucher** [comment]
@lapagept Which module are you are you trying to install on odoo 8.0 version?
