### ISSUE TITLE
[10.0] web_domain_field - TypeError: unhashable type: 'list' when building domain from list

### ISSUE THREAD

**Issue by kk8888-2016** [OCA/web#840]
Hi.

I try to build the domain from ids of a many2many fields as follows

<field name="product_id_domain" invisible="1"/>
<field name="product_id" domain="product_id_domain"/>
The field used as domain must provide the domain as a JSON encoded string.

product_id_domain = fields.Char(
    compute="_compute_product_id_domain",
    readonly=True,
    store=False,
)

@api.multi
@api.depends('name')
def _compute_product_id_domain(self):
    for rec in self:
        rec.product_id_domain = json.dumps(
            [('id', 'in', x2manyfield.ids)]
        )

I got the following error in the client, any idea for help. Thanks in advance.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/models.py", line 1600, in name_search
    return self._name_search(name, args, operator, limit=limit)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/models.py", line 1613, in _name_search
    ids = self._search(args, limit=limit, access_rights_uid=access_rights_uid)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/models.py", line 4224, in _search
    query = self._where_calc(args)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/models.py", line 4023, in _where_calc
    e = expression.expression(domain, self)
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/osv/expression.py", line 640, in __init__
    self.expression = distribute_not(normalize_domain(domain))
  File "/opt/bitnami/apps/odoo/lib/odoo-10.0.post20170615-py2.7.egg/odoo/osv/expression.py", line 289, in distribute_not
    elif token in DOMAIN_OPERATORS_NEGATION:
TypeError: unhashable type: 'list'

**Comment by lmignon** [comment]
@kk8888-2016 How do you use the domain field into your view?

**Comment by kk8888-2016** [comment]
@lmignon 

Thanks you for quick response, I fixed the problem as my typo in the code. 
rec.product_id_domain = json.dumps(
['id', 'in', x2manyfield.ids]
)
