### ISSUE TITLE
[9.0] web_decimal_numpad_dot

### ISSUE THREAD

**Issue by mtbochaca** [OCA/web#848]
Error when press the numpad dot key:

Uncaught TypeError: Cannot read property 'prop' of undefined
http://192.168.1.6:8069/web_decimal_numpad_dot/static/src/js/numpad_dot.js:28
Traceback:
TypeError: Cannot read property 'prop' of undefined
    at Class.numpad_dot_replace (http://192.168.1.6:8069/web_decimal_numpad_dot/static/src/js/numpad_dot.js:28:36)
    at HTMLSpanElement.<anonymous> (http://192.168.1.6:8069/web/static/src/js/framework/widget.js:398:23)
    at HTMLSpanElement.dispatch (http://192.168.1.6:8069/web/static/lib/jquery/jquery.js:4641:58)
    at HTMLSpanElement.elemData.handle (http://192.168.1.6:8069/web/static/lib/jquery/jquery.js:4309:63)

Odoo 9 - Language Catalan.

**Comment by pedrobaeza** [comment]
Please try to reproduce it on runbot.

**Comment by pedrobaeza** [comment]
Closing as no response

**Comment by mtbochaca** [comment]
Sorry!!!!
In the runbot the problem is the same:
Uncaught TypeError: Cannot read property 'prop' of undefined
http://3322398-9-0-903617.runbot1.odoo-community.org/web/content/545-9bca5ba/web.assets_backend.js:4642
Traceback:
TypeError: Cannot read property 'prop' of undefined
    at Class.numpad_dot_replace (http://3322398-9-0-903617.runbot1.odoo-community.org/web/content/545-9bca5ba/web.assets_backend.js:4642:45)
    at HTMLSpanElement.<anonymous> (http://3322398-9-0-903617.runbot1.odoo-community.org/web/content/372-89f65ef/web.assets_common.js:2646:11)
    at HTMLSpanElement.dispatch (http://3322398-9-0-903617.runbot1.odoo-community.org/web/content/372-89f65ef/web.assets_common.js:740:451)
    at HTMLSpanElement.elemData.handle (http://3322398-9-0-903617.runbot1.odoo-community.org/web/content/372-89f65ef/web.assets_common.js:713:173)
