### ISSUE TITLE
Bokeh requirements is breaking travis builds

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/web#893]
Error:
```
Collecting tornado>=4.3 (from bokeh==0.12.7)
  Downloading tornado-5.0.tar.gz (504kB)
    100% |████████████████████████████████| 512kB 2.7MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-QN3nSj/tornado/setup.py", line 146, in <module>
        raise ImportError("Tornado requires an up-to-date SSL module. This means "
    ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).
```
example: https://travis-ci.org/OCA/web/jobs/350854855

Two options come to my mind:
* Force to use a lower version of tornado.
* Use python 2.7.9 or greater.

Any advise here @moylop260 ?

cc @hveficent

**Comment by LoisRForgeFlow** [comment]
fixes here https://github.com/OCA/web/pull/909/files
